assets/jcustomer/reset-unomi-root-password.py, mixins/jcustomer.yml, packages/jahia/link-to-jcustomer.yml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v4.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1535
I tried to think of a simple way to do it but it was more complex than it seemed because of the `export` command in `setenv` file.
The way I choose to go with allow the user to put single/double quotes, dollar signs and other special characters in their jcustomer password.
I've tested some scenarios and it seems to work pretty well
=> PAAS-1535: fix karaf password when containing dollar sign

assets/jahia/update-jcustomer-password-in-jahia.py, packages/jahia/link-to-jcustomer.yml, packages/jahia/set-jcustomer-password-in-jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1601
For example if the password is `Password\01`, we need to write `Password\\01` in the cfg file.
=> PAAS-1601: Escape backslashes inside jexperience cfg file

packages/jahia/link-to-jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1654
=> PAAS-1654: Install v2.2.0 of jExperience instead of 2.1.0

packages/one-shot/remove-duplicate-db-users.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1683
Few things that changed from the previous version -
1. Able to delete multiple wrong users present instead of just one in the earlier version.
2. Package to run on one node instead of sqldb nodegroup.
3. `DROP USER` is used instead of `DELETE FROM` as it replicates the action of removing of user on all galera nodes and also we will be able to recreate the removed user in future if needed.
=> PAAS-1683: Improve query to handle multiple wrong user deletion

packages/jahia/migrations/migrate-to-v8.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1708
The only update of jahia-cloud.cfg was the "timeout server" line so rather than overwriting the whole file, we can just sed
=> PAAS-1708: fix haproxy conf overwritten in migration-v8

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1939
=> PAAS-1939: set loglevel to ERROR when ssh to karaf console

packages/jcustomer/install.yml
This setting is necessary because used in OnBeforeInstall event and there is no other way to get the shortdomain in this event (even if it is passed as a parameter)
=> PAAS-1854: add shortdomain setting and use it

packages/jcustomer/migrations/migrate-to-v11.yaml
The identification of jCustomer environments used for AS doesn't work because of the prefix being {{-context}} all the time:
https://github.com/Jahia/jelastic-packages/pull/288/files#diff-6444e82afd59550ec80adf6dbe1ed0df20dedb578c71bf46606489fdd8e669c6R203
This is due to... drum rolls... Jelastic! I think that {{${something:something_else}}} is going to check if something exists as a global or local variable, and if not it will use something_else, but before it is passed to the container to be executed (like global variables are replaced by their value for instance).
=> PAAS-1970: fix detection of non dedicated jcustomer envs

packages/jcustomer/migrations/v11_assets/restore_for_ec_migration.yml, packages/one-shot/paas-2029-fix-analyser-missing-in-indices-after-ec-migration.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2029
* to fix already migrated to EC: get mappings from "old" ES nodes (so start/stop elasticsearch on them)
* for migration manifest: get mappings from restored indices
=> PAAS-2029 create indices using the previous mappings

packages/jahia/migrations/migrate-to-v14.yaml
I would advise to test it again before merging.
Output looks like this:
- Jahia 7 (normal pipe): `162|Resolved||cluster/local||2.5.0|graphql-dxm-provider`
- Jahia 8 (long pipe): `162│Resolved││cluster/local││2.5.0│graphql-dxm-provider`
=> PAAS-1786: replace stupid double split (doesn't work) with ugly regex

mixins/jahia.yml, packages/common/restore.yml, packages/jahia/link-to-jcustomer.yml, packages/jahia/manage-module.yml, packages/jahia/migrations/migrate-to-v15.yaml, packages/jahia/unlink-jahia-jcustomer.yml, packages/jahia/update-events.yml, packages/one-shot/ccm-103-update-to-tomcat-9-0-54.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1916
- fixed the restore not working because of Jahia not available when trying to uninstall modules (btw the `healthcheck-cluster` module uninstall is useless)
- renaming and improving different actions
=> Paas 1916 manage modules with jahia api

packages/jcustomer/migrations/migrate-to-v14.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2109
=> PAAS-2109: add missing Datadog tracer jar in migration package

packages/jahia/migrations/migrate-to-v17.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2024
=> PAAS-2024 set ImageMagick7 memory limit to 2GiB

mixins/jahia.yml, mixins/jcustomer.yml, packages/jahia/link-to-jcustomer.yml, packages/jahia/unlink-jahia-jcustomer.yml, packages/jcustomer/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2064
To avoid having a very complex `deleteEnvLinkJcustomer` action with many things to do on Jahia envs, I decided to update the unlink package so it can be used on each linked Jahia env when we delete a jCustomer env.
I feel like the code is clearer that way, and we avoid doing the same things in two different places, but let me know if it works for you @amitc-jahia and @laurentfufu
=> PAAS-2064: remove kibana-dashboards-provider and jexperience-dashboard when unlinking or deleting jCustomer

mixins/jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2210
I don't really see the point of fixing this since the ampersand is a forbidden special character for karaf password (Jahia Cloud won't accept it) but this does the magic anyway
=> PAAS-2210: fix datadog conf file when ampersand present in karaf password

assets/jahia/as-restore-modules-provisioning-file.yaml, assets/jahia/jcustomer-restore-module-provisioning-file.yaml, packages/common/restore.yml
The code refactoring is going to be annoying for the code review so let me explain here what this PR is mainly about:
* for Jahia 8: use of a provisioning file to install the right version of jExperience and AS before starting Jahia (if required)
* which means the modules should be running the right versions and confs should be up-to-date when Jahia starts, if not then it means there is an issue
* for Jahia 7 the old method will be used since the provisioning won't work, which means we can't even install the modules before starting Jahia if they were not installed in the backup
* this means we have to check many things because if modules were present in the backup, then the conf could have been updated before starting …
=> PAAS-2217: use provisioning to install AS/jExperience modules before starting Jahia. Refactor code

assets/common/rclone-cron
JIRA issue: https://jira.jahia.org/browse/PAAS-2193
=> PAAS-2193: add random delay before running rclone-logs script

mixins/common.yml, packages/common/backup.yml, packages/common/restore.yml
compatibility with old ovh backups that are stored on aws
=> PAAS-2266: fix ovh backup region to gra2 even. Handle backward

packages/jahia/restore-haproxy-config.yml
To be able to completely reset the HAProxy config, for instance in case a migration fails after disabling the healthcheck.
=> Add restore-haproxy-config package

mixins/haproxy.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2261
Short description: add logic to haproxy actions removeProcNodeFromHaproxy & removeBrowsingNodeFromHaproxy to allow more time for sessions to end when removing a node, thus reducing the chance of haproxy triggering a datadog alert
=> PAAS-2261: Wait 120s for sessions to end on haproxy when an action removes a node

packages/jahia/migrations/migrate-to-v23.yaml, packages/jahia/migrations/v23_assets/strongswan_connections_status.py
JIRA issue: https://jira.jahia.org/browse/PAAS-2270
The `strongswan_connections_status.py` script was not working anymore since we upgraded Datadog to v7 (we had bytes instead of a string when running the command `strongswan statusall`.
I also took advantage of this PR to install the package `gnureadline` to fix the Python3 shell (the arrows, tabulation and other keys wouldn't not behave as expected, making the usage of REPL very difficult)
=> PAAS-2270: fix strongswan custom check after datadog-agent upgrade to v7

assets/haproxy/haproxy-jahia-cloud.cfg, mixins/haproxy.yml, packages/jahia/migrations/migrate-to-v24.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2300
since a production environment has a `/etc/haproxy/blacklisted_ips.txt` file used by a custom client configuration, i preferred to stick with this path and name for the file (although i would have preferred a non-racist name).
Another environment with a manually set up denylist also uses this same name. In addition, I have manually moved the configuration block within `jahia-cloud.cfg` to the same location.
=> PAAS-2300 add an ip denylist configuration

packages/jahia/consistency-check.yml, packages/jahia/migrations/migrate-to-v26.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2372
Short description: update GraphQL to 2.18. Upgrade consistency-check package to reflect the change.
=> PAAS-2372: update GraphQL to 2.18

packages/jahia/migrations/migrate-to-v26.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2219
Short description: rollback tomcat version switch in the last migration package.
=> PAAS-2219: rollback tomcat version change

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2219
Short description: Add a last resort refresh & restart of SAM and GraphQL modules if tomcat is started, but the health check still fails.
=> PAAS-2219: modify Jahia startup

packages/jahia/augmented-search-install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2447
=> PAAS-2447: Install Augmented Search 3.5.0 instead of 3.4.2

mixins/jahia.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v31.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2449
- Add "setupDatadogAgentStorage" action to Jahia install package.
- Add nfs monitoring on jahia nodes when needed.
=> PAAS-2449: add datadog config to storage nodes

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2616
=> PAAS-2616: Fix module state not renamed in 'local' dump

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2608
=> PAAS-2608: fix case when curl_extra_args is empty in callProvisioningAPI

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2662
Short description: Add a safety net by making sure FRO is forced off if enabling it failed.
=> PAAS-2662: handle error when enabling FRO

mixins/common.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-XXX
=> PAAS-2689: add missing systemctl daemon-reload after adding datadog-agent override

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2740
=> PAAS-2740: Install jExperience 2.9.0 instead of 2.8.0

packages/jahia/migrations/migrate-to-v38.yaml, packages/jahia/migrations/v38_assets/tomcat_tmp_cleanup.service, packages/jahia/migrations/v38_assets/tomcat_tmp_cleanup.timer
JIRA issue: https://jira.jahia.org/browse/PAAS-2392
Short description: Add a systemd timer (and his service) to take care of cleaning up tomcat temporary folder.
=> PAAS-2392:Add weekly cleanup for tomcat temp folder

assets/common/set_dd_tags.sh, assets/storage/storage_jahia_custom_metrics.py, assets/storage/storage_jahia_custom_metrics.yaml, mixins/jahia.yml, packages/jahia/migrations/migrate-to-v38.yaml, packages/jahia/migrations/v38_assets/augmented_search.py, packages/jahia/migrations/v38_assets/jahia_custom_metrics.py
JIRA issue: https://jira.jahia.org/browse/PAAS-2658
* I decided to add the AS indices check to the existing AS custom check to make things easier, and the datastore check needs to be run on a storage node
* Since checks are not running on the same nodes, we can't have a single metric so I decided to a metric that will look like `jahia.custom_metrics.customer_disk_usage.<datastore|database|augmented_search>` and we will have to add the numbers in the widget.
* For the datastore check on storage nodes, I decided to give `dd-agent` the permission to run `sudo du`, the other option was to run the `du` command as a cron (run by root) and put the result in a file that can then be read by dd-agent. **If you prefer this solution** let me know and I will do the required changes …
=> PAAS-2658: add new checks for Jahia env disk space

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2856
Short description: Add proxysql restart before tomcat first start to make sure everything is in order.
=> PAAS-2856: Add proxysql restart before tomcat starts

mixins/jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-3001
Short description: Run tag script before starting dd agent on jcustomer
=> PAAS-3001: set tags before starting dd agent

packages/jcustomer/reindexation.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-3019
Short description: Fix bug where aliases and ILM policies were not carried over during a reindexation
=> PAAS-3019: fix jCustomer reindexation bug

README.md, assets/common/hn_nodes_list.py, assets/common/hn_upgrade_plan.py
JIRA issue: https://jira.jahia.org/browse/PAAS-2945
According to @Ronan-Gorain, it is not recommended by Virtuozzo to upgrade two or more HNs simultaneously so this PR might be useless if we stick to that (but it doesn't hurt to add a check regardless).
Regarding the SLBs, they are already included in the nodegroups we check to create the groups so nothing to add on this side
=> PAAS-2945: do not in clude core HNs in the same group for upgrades

mixins/mariadb.yml, packages/common/restore.yml
Nothing really blocker but these could lead to issues in a near future so better to fix it now (and very low impact)
- the restore of a single DB env to a galera cluster env doesn't work anymore because the `xtrabackup_galera_info` file doesn't exist when trying to create the `grastate.dat` file, which leads to missing info and MariaDB startup failing. It used to work with SystemV for some reason despite `grastate.dat` having missing values but it doesn't work anymore since we moved to SystemD so it needs to be addressed by saving the `xtrabackup_galera_info` file before purging the folder in case the backup doesn't include it
- the logrotate file won't be taken into account if permissions are not set to 644 after …
=> PAAS-3048: improve startup of MariaDB for single DB

packages/jahia/update-graphql-dxm-provider.yaml
Since updating graphql triggers a refresh of SAM module, which can take time, better take profit of the new options of `checkJahiaHealth` to loop instead of doing a single check that could fail
=> Ninja: Loop on healthcheck after graphql update

mixins/jcustomer.yml
Adding the `Detected: .* profiles merged` pattern
=> PAAS-3173: add a pattern to detect Unomi migrations

packages/common/restore.yml
There was an issue with Selenium tests because the PID changed during the startup check. This is because we check jCustomer startup right after restarting the nodes through an API call, and it can be too soon (jCustomer not done stopping yet) so the PID is the one before restart.
A 30s sleep should do the trick
=> PAAS-3173: wait for jCustomer to actually restart before checking startup
