assets/haproxy/haproxy-10-jahia.cfg, assets/haproxy/haproxy-11-proc.cfg
JIRA issue: https://jira.jahia.org/browse/PAAS-1536
need to use /modules/healthcheck to avoid redirection issues
=> PAAS-1536: Fix healthcheck URL

packages/jcustomer/install.yml, packages/jcustomer/update-events.yml, packages/jcustomer/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1509
=> PAAS-1509 fix empty password setting not working and jcustomer upgrade

README.md, assets/common/backrest.py, assets/common/lib_aws.py, assets/common/lib_azure.py, assets/common/revisionNode.py, assets/elasticsearch/elasticsearch.py, mixins/common.yml, mixins/elasticsearch.yml, mixins/mariadb.yml, packages/common/auto_backup.yml, packages/common/auto_backup_control.yml, packages/common/backup.yml, packages/common/listbackup.yml, packages/common/restore.yml, packages/jcustomer/install.yml, packages/jcustomer/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1510
Good luck :trollface:
=> Paas 1510 move backup to jelastic packages

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1510
=> PAAS-1510: Fix jCustomer restore final check

packages/jahia/migrations/jahia_node_not_in_haproxy_pool.py, packages/jahia/migrations/jahia_node_not_in_haproxy_pool.yaml, packages/jahia/migrations/migrate-to-v5.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1534
=> PAAS-1534: Add custom Datadog check for jahia node not in haproxy pool

assets/database/jahia_override.lib, mixins/mariadb.yml, packages/jahia/migrations/migrate-to-v5.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1437
=> PAAS-1437: Prevent MariaDB auto-restart when updating cloudlets count

packages/jahia/ipsec.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1544
=> PAAS-1544: restart Strongswan daemon instead of reloading

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1510
=> PAAS-1510: fix revisionNode.py not being run as root

assets/jcustomer/reset-unomi-root-password.py
JIRA issue: https://jira.jahia.org/browse/PAAS-1510
=> PAAS-1510: fix jcustomer password ending with a backslash

mixins/jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1535
=> PAAS-1535: fix jcustomer password with trailing backslash for DD conf

mixins/jahia.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1577
=> PAAS-1577: Remove Jahia 7.3.1.1

assets/jcustomer/reset-unomi-root-password.py, packages/jcustomer/set-unomi-root-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1546
=> PAAS-1546: Remove datadog file check from reset password script

packages/jcustomer/migrations/migrate-to-v4.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1535
=> PAAS-1535: fix jcustomer healthcheck in migration-v4

mixins/common.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1582
=> PAAS-1582 regex now handle release tag by capturing between slashs

packages/one-shot/fix-jahia-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1594
=> PAAS-1594: remove old (duplicate) events.

packages/jcustomer/install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1595
=> PAAS-1595: fix jcustomer random password empty

packages/jahia/link-to-jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1588
=> PAAS-1588: Update jExperience (1.11.4/2.0.1)

assets/haproxy/haproxy_one_remaining_browsing.py, mixins/haproxy.yml, packages/jahia/migrations/migrate-to-v6.yaml, packages/one-shot/add-haproxy-one-remaining-browsing-script.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1598
- I created a separate package to fix only that issue just in case (in the one-shot folder). Otherwise it will be fixed during next release with the migration package, confirmed with Kevin: it's not urgent since it only impacts new environments
- The migration-v6 package will conflict with other PRs so depending on which one is merged first, will need to be rebased
=> PAAS-1598: add missing haproxy_one_remaining_browsing.py

assets/haproxy/haproxy_one_remaining_browsing.py, packages/jahia/migrations/migrate-to-v6.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1598
=> PAAS-1598: fix url in haproxy_one_remaining_browsing.py

mixins/jcustomer.yml, packages/jahia/install.yml, packages/jahia/link-to-jcustomer.yml, packages/jahia/migrations/migrate-to-v6.yaml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v5.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1557
=> PAAS-1557: Use non-default apiKey for jCustomer provider

packages/jahia/migrations/migrate-to-v6.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1557
=> PAAS-1557: Remove default jcustomer key file from jahia

packages/jcustomer/migrations/migrate-to-v5.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1557
=> PAAS-1557: Add jcustomer healthcheck before post actions

assets/database/mysql-init.d, mixins/mariadb.yml, packages/jahia/migrations/migrate-to-v6.yaml, packages/jahia/migrations/v6_assets/MariaDB.repo
JIRA issue: https://jira.jahia.org/browse/PAAS-1504
=> PAAS-1504: switch SST method to mariabackup

mixins/mariadb.yml, packages/common/backup.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1505
=> PAAS-1505: remove installMariaDBBackup action

mixins/elasticsearch.yml, packages/common/backup.yml, packages/common/restore.yml, packages/jcustomer/install.yml, packages/jcustomer/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1610
=> PAAS-1610: remove jcustomer 1.4 and es 5

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v6.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1580
=> PAAS-1580: force hazelcast to use main network interface

packages/jahia/migrations/migrate-to-v6.yaml, packages/jahia/migrations/v6_assets/charon_resolve.conf, packages/jahia/migrations/v6_assets/strongswan_updown_script.sh
JIRA issue: https://jira.jahia.org/browse/PAAS-1592
=> PAAS-1592 add dns split for ipsec in migration script

packages/jahia/migrations/migrate-to-v6.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1592
=> PAAS-1592 fix updown script detection in migration manifest

packages/jahia/link-to-jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1624
I hope you are not dyslexic
=> PAAS-1624: Install jExperience 2.1.0 for Jahia 8.0.2.0+

packages/jahia/migrations/migrate-to-v6.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1592
=> PAAS-1592 fix silly grep without input in migration manifest

packages/jahia/migrations/migrate-to-v6.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1592
=> PAAS-1592 fix the inverted presence test of dnsmasq

mixins/jcustomer.yml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v6.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1578
=> PAAS-1578  Set more reliable values for UNOMI_CLUSTER_*_ADDRESS

packages/jahia/migrations/migrate-to-v6.yaml, packages/one-shot/install-qpress-socat.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1646
I also fixed the migration package, even though it's a bit useless
=> PAAS-1646: One-shot package to install qpress and socat on DB nodes

packages/jahia/migrations/migrate-to-v6.yaml, packages/one-shot/install-qpress-socat.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1646
=> PAAS-1646: fix qpress/socat installation

packages/jcustomer/migrations/migrate-to-v6.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1578
=> PAAS-1578 update envvars only, split restart to another action

mixins/common.yml, mixins/elasticsearch.yml, mixins/haproxy.yml, mixins/jahia.yml, mixins/jcustomer.yml, mixins/mariadb.yml, packages/jahia/link-to-jcustomer.yml, packages/jahia/migrations/migrate-to-v5.yaml, packages/jahia/migrations/migrate-to-v6.yaml, packages/jahia/perf-test-step1.yml, packages/jahia/set-jcustomer-password-in-jahia.yml, packages/jcustomer/set-unomi-root-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1599
It's boring to review, but please read carefully as there is a lot of different cases.
=> PAAS-1599: Use cURL to DL files and exit if fails

packages/one-shot/fix-context-patch-index-configuraton.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1643
=> PAAS-1643: Package to fix 'context-patch' index configuration

packages/jcustomer/migrations/migrate-to-v6.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1578
=> PAAS-1578 sleepy me

packages/jcustomer/migrations/migrate-to-v6.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1578
=> PAAS-1578 i guess i need some rest

mixins/mariadb.yml, packages/jahia/migrations/migrate-to-v5.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1599
=> PAAS-1599: Fix cURL not creating subdir when needed

mixins/mariadb.yml, packages/jahia/migrations/migrate-to-v5.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1599
This time it works :grimacing:
=> PAAS-1599: Fix cURL not creating subdir when needed (for real)

packages/one-shot/fix-context-patch-index-configuraton.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1643
=> PAAS-1643: Fix context-patch index for AS+jCustomer envs

packages/jahia/install.yml, packages/jahia/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1613
=> PAAS-1613: Add dockerTagSuffix parameter to Jahia install and upgrade packages

assets/haproxy/haproxy-10-jahia.cfg, assets/haproxy/haproxy-11-proc.cfg, packages/jahia/migrations/migrate-to-v7.yaml, packages/jahia/migrations/v7_assets/jahia_node_not_in_haproxy_pool.py
JIRA issue: https://jira.jahia.org/browse/PAAS-1653
=> PAAS-1653: Fix custom check script for jahia_node_not_in_haproxy_pool monitor

packages/jahia/migrations/migrate-to-v7.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1651
=> PAAS-1651 download ipsec_updown.sh as root

packages/one-shot/paas-1669-fix-jahia-8030.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1669
=> PAAS-1669: One-shot package to fix Jahia 8.0.3.0 envs

packages/jahia/migrations/migrate-to-v7.yaml, packages/jahia/migrations/v7_assets/strongswan_override
JIRA issue: https://jira.jahia.org/browse/PAAS-1667
=> PAAS-1667 add force establishing ipsec conn at strongswan start

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v7.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1658
=> PAAS-1658 add JELASTIC_EXPOSE=false to sqldb nodegroup

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v7.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1645
=> PAAS-1645 install ImageMagick7 from remi's repo instead of AppImage

assets/haproxy/haproxy-10-jahia.cfg, assets/haproxy/haproxy-11-proc.cfg, assets/haproxy/haproxy-jahia-cloud.cfg, assets/haproxy/haproxy-sysconfig, assets/haproxy/haproxy_one_remaining_browsing.py, mixins/haproxy.yml, packages/common/backup.yml, packages/common/restore.yml, packages/jahia/manage-auth-basic.yml, packages/jahia/migrations/migrate-to-v7.yaml, packages/jahia/rewrite-rules.yml, packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1321
=> PAAS-1321: improve haproxy conf management

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1653
=> PAAS-1653: Remove access log pattern update from mixin and handle in Base image instead

packages/jahia/migrations/migrate-to-v7.yaml, packages/jahia/rewrite-rules.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1321
=> Paas 1321 rethink haproxy conf

packages/common/restore.yml, packages/jahia/migrations/migrate-to-v7.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1321
=> PAAS-1321: fix permission and awk issues

packages/common/backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1668
=> PAAS-1668: fix jcustomer backup retention

packages/jahia/migrations/migrate-to-v7.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1675
=> PAAS-1675: restart jahia systematically in migrate-to-v7 package

packages/jahia/migrations/migrate-to-v7.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1675
=> PAAS-1675: Missing $ for variable in grep check

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v8.yaml, packages/jahia/migrations/v8_assets/jahia_node_not_in_haproxy_pool.py, packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1674
=> PAAS-1674: add HAPROXY_NODES_COUNT env var

packages/jahia/migrations/migrate-to-v8.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1664
=> PAAS-1664: Enable tomcat garbage collection metrics

packages/jahia/migrations/migrate-to-v8.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1685
=> PAAS-1685 fix getJvmPid function in tomcat init script

packages/one-shot/remove-duplicate-db-users.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1683
=> PAAS-1683: Remove duplicate db users on existing environments

mixins/jahia.yml, packages/common/backup.yml, packages/common/restore.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v8.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1579
=> PAAS-1579 Make maxPostSize tunable

packages/jahia/migrations/migrate-to-v8.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1685
=> PAAS-1685 fix sed modifying a wrong line too

packages/common/backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1579
=> PAAS-1579 fix grep not using Extended regex

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v8.yaml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v7.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1631
=> PAAS-1631: Add organization name in env vars

packages/jahia/ipsec.yml, packages/jahia/rewrite-rules.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1632
=> PAAS-1632: Define vault secret path in ipsec and rewrite-rules packages

packages/jahia/ipsec.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1632
=> PAAS-1632: Fix secret path name for ipsec package

packages/jahia/link-to-jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1706
I'm tired of this kind of stupid PRs...
=> PAAS-1706: Install jExperience 1.11.5 instead of 1.11.6 for Jahia 7 envs

mixins/haproxy.yml, packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1496
=> PAAS-1496: Reset haproxy backends after env start

mixins/haproxy.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1496
Remove duplicate addition of proc node to haproxy pool at Jahia env creation
=> PAAS-1496: Fix Jahia env create

packages/jahia/rewrite-rules.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1575
=> PAAS-1575 fix haprox--reload.sh not launch as root

packages/jahia/migrations/migrate-to-v8.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1575
=> PAAS-1575 fix migration script (/etc/sysconfig/haproxy was not updated)

packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v7.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1325
=> PAAS-1325: allow Workato & IT OVH firewall IP addresses

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v8.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1705
I also "fixed" the `addMaxPostSize` action of the migration package so that it is idempotent.
=> PAAS-1705: Enable 'NativeMemoryTracking' on all Jahia nodes

assets/haproxy/haproxy-jahia-cloud.cfg, assets/haproxy/haproxy-sysconfig, mixins/common.yml, mixins/haproxy.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v8.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1708
=> PAAS-1708: Add 'haproxy_cfg_timeout_server' config envvar

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1714
=> PAAS-1714 fix copyApp for it to nod add duplicate entries in conf files

mixins/elasticsearch.yml, mixins/haproxy.yml, mixins/jahia.yml, mixins/jcustomer.yml, mixins/mariadb.yml, packages/jahia/migrations/migrate-to-v8.yaml, packages/jcustomer/migrations/migrate-to-v7.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1542
=> PAAS-1542: Temporarily disable IO check

mixins/common.yml, mixins/jahia.yml, packages/jahia/link-to-jcustomer.yml, packages/jahia/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1700
=> PAAS-1700: Clean code related to Jahia 8.0.1.0

packages/jahia/migrations/migrate-to-v8.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1542
=> PAAS-1542: Fix disableIoCheck in Jahia migration-to-v8

packages/jahia/reset-haproxy-backends.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1719
=> PAAS-1719: Add 'reset-haproxy-backends' package

mixins/common.yml, mixins/elasticsearch.yml, mixins/haproxy.yml, mixins/jahia.yml, mixins/jcustomer.yml, mixins/mariadb.yml, packages/jahia/migrations/migrate-to-v8.yaml, packages/jcustomer/migrations/migrate-to-v7.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1687
=> PAAS-1687: Add DD custom checks validation

packages/jahia/ipsec.yml, packages/jahia/migrations/v8_assets/strongswan_connections_status.py
JIRA issue: https://jira.jahia.org/browse/PAAS-1720
Using the datadog custom check to check connections in case there is an HA one
=> Paas 1720 fix ipsec package

mixins/jcustomer.yml, packages/jahia/link-to-jcustomer.yml, packages/jahia/update-events.yml, packages/jcustomer/install.yml, packages/jcustomer/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1715
I also added the action at jCustomer env restart in case the env was stopped during scaling of a linked Jahia env.
=> PAAS-1715: Refresh jCustomer allowed IPs on Jahia browsing scale in/out

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1732
=> PAAS-1732: fix infinite loop in installModuleIfNotPresent action

packages/jahia/link-to-jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1715
=> PAAS-1715: Fix regression on 'link-to-jcustomer' package

mixins/jcustomer.yml, packages/jcustomer/install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1715
FYI, it's not possible to use actions inside `onBeforeInstall`, you can only put JS in there...
=> PAAS-1715: Fix jCustomer env creation

mixins/jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1715
=> PAAS-1715: Fixes

packages/jahia/migrations/v9_assets/jahia_node_not_in_haproxy_pool.py
JIRA issue: https://jira.jahia.org/browse/PAAS-1693
=> PAAS-1693: Run check if node is up over 30 mins

packages/jahia/rewrite-rules.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1745
=> PAAS-1745: Handle backslash escape sequences in a better way

assets/common/check_before_hn_upgrade.py
JIRA issue: https://jira.jahia.org/browse/PAAS-1428
=> PAAS-1428: add script to check hardware nodes before system upgrade

assets/common/papi.py, mixins/common.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v9.yaml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v8.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1686
=> Paas 1686 papi python lib

mixins/jcustomer.yml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v8.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1735
=> PAAS-1735: remove wrong ip from workato ip list

mixins/common.yml, mixins/haproxy.yml, mixins/jahia.yml, packages/jahia/ipsec.yml, packages/jahia/rewrite-rules.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1736
=> Paas 1736 mixins vault

mixins/common.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1736
=> PAAS-1736: fix wrong RC when deleting secret

mixins/common.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-590
=> PAAS-590: fix typos in mute/unmute actions

mixins/common.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1736
=> PAAS-1736: add recursive mode to vaultSecretsList action

mixins/common.yml, packages/jahia/update-events.yml, packages/jcustomer/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1635
=> PAAS-1635: remove vault secrets at env deletion

mixins/common.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-590
=> PAAS-590: fix typos (again) in mute/unmute actions

mixins/common.yml, mixins/elasticsearch.yml, mixins/haproxy.yml, mixins/jahia.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v9.yaml, packages/jahia/rewrite-rules.yml, packages/jahia/set-jcustomer-password-in-jahia.yml, packages/jahia/update-events.yml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v8.yaml, packages/jcustomer/set-unomi-root-password.yml, packages/jcustomer/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1760
=> PAAS-1760: install jq and python everywhere at env creation

packages/common/backup.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1729
=> PAAS-1729: backup jcustomer env vars

packages/common/backup.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1729
=> PAAS-1729: fix unomi env var prefix in backup/restore

packages/jahia/migrations/migrate-to-v9.yaml, packages/jcustomer/migrations/migrate-to-v8.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1760
=> PAAS-1760: fix migration packages, install jq before healthchecks

mixins/elasticsearch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1763
=> PAAS-1763: use local variables to easily ofuscate AWS creds

packages/jcustomer/migrations/migrate-to-v8.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1380
=> PAAS-1380 migrate to v8: add debug logs for jetty io

mixins/jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1762
=> PAAS-1762: Fix env link deletion when deleting jCustomer env

packages/jahia/migrations/migrate-to-v9.yaml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v8.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1764
=> PAAS-1764: add vault to jcustomer environments

packages/jcustomer/migrations/migrate-to-v8.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1380
=> PAAS-1380 make addJettyIODebug idempotent

packages/jahia/install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1764
=> PAAS-1764: add missing vault env vars on jahia db nodes

packages/jcustomer/migrations/migrate-to-v8.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1380
=> PAAS-1380 fix yaml

packages/jahia/migrations/migrate-to-v9.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1723
=> PAAS-1723: fix indentation

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1723
=> PAAS-1723: fix variable naming

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1723
=> PAAS-1723: change last remaining 'time' variable to 'tries'

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v9.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1640
=> PAAS-1640 add jvmRoute to tomcat

packages/jahia/migrations/migrate-to-v9.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1723
=> PAAS-1723: do not switch master if single db node in migration script

mixins/jahia.yml, packages/jahia/configure-apm.yaml, packages/jahia/migrations/migrate-to-v9.yaml
enabled
JIRA issue: https://jira.jahia.org/browse/PAAS-1767
=> PAAS-1767: apply datadog apm settings for jahia process only when APM is

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v9.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1767
=> PAAS-1767: add missing space :facepalm

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v9.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1288
=> PAAS-1288 install Distributed Sessions module

assets/common/lib_aws.py
JIRA issue: https://jira.jahia.org/browse/PAAS-754
=> PAAS-754: add functions to list and delete files on S3

assets/haproxy/haproxy-jahia-cloud.cfg, packages/jahia/migrations/migrate-to-v10.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1805
=> PAAS-1805: Remove HSTS header at HAProxy level

mixins/jahia.yml, packages/jahia/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1829
In the end I had to refactor a few things, so gl&hf
=> PAAS-1829: Fix usage of docker tag vs jahia version in upgrade package

packages/one-shot/install-jahia-workflow-processes-patch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1819
=> PAAS-1819: Update the correct patch path

packages/jahia/migrations/migrate-to-v10.yaml, packages/jcustomer/migrations/migrate-to-v9.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1811
=> PAAS-1811 set envvar envmode if needed, use it for dd tag

packages/jahia/migrations/migrate-to-v10.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1811
=> PAAS-1811 fix missing single quote

packages/jcustomer/migrations/migrate-to-v9.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1811
=> PAAS-1811 fix missing single quote (dejà vu)

packages/jahia/migrations/migrate-to-v10.yaml, packages/jcustomer/migrations/migrate-to-v9.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1811
=> PAAS-1811 add missing quotes in test envvar conditions

packages/one-shot/install-jahia-workflow-processes-patch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1819
=> PAAS-1819: Re-work one shot package to install Jahia patch

mixins/common.yml, packages/jahia/migrations/migrate-to-v10.yaml, packages/jcustomer/migrations/migrate-to-v9.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1844
=> PAAS-1844: Fix migration package actions

packages/one-shot/install-jahia-workflow-processes-patch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1856
=> PAAS-1856: Handle HAProxy pool in install-jahia-workflow-processes-patch package

packages/common/start-nodes.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1835
=> PAAS-1835: fix typo

packages/jcustomer/install.yml, packages/jcustomer/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1868
=> PAAS-1868: Add docker tag suffix for jcustomer and es

mixins/jcustomer.yml, packages/jahia/link-to-jcustomer.yml, packages/jahia/unlink-jahia-jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1871
=> PAAS-1871: Package to unlink jahia and jcustomer

mixins/common.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1841
=> PAAS-1841: Mute & Unmute datadog hosts when restoring a backup

mixins/jahia.yml, packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1739
=> PAAS-1739: Improve Jahia/jCustomer link management when Jahia is deleted

packages/jahia/link-to-jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1878
=> PAAS-1878: Install jExperience 2.2.1 for Jahia 8.1

packages/jahia/link-to-jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1780
=> PAAS-1780: fix envlink bug for jcustomer environments

packages/jcustomer/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1880
=> PAAS-1880: Fix jCustomer package confusing docker tag and product version

packages/jcustomer/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1880
=> PAAS-1880: Fix jCustomer upgrade

mixins/common.yml, mixins/jahia.yml, mixins/jcustomer.yml, packages/common/restore.yml, packages/jahia/migrations/migrate-to-v11.yaml, packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1740
=> PAAS-1740: improve jahia/jcustomer envlink at jcustomer deletion

packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v10.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1896
=> PAAS-1896 remove jetty.io ERROR log level

packages/jahia/migrations/migrate-to-v11.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1901
Short description: One character, big consequences (bis repetita)
=> PAAS-1901 fix silly single quote character

packages/one-shot/ccm-103-update-to-tomcat-9-0-54.yaml
JIRA issue: https://jira.jahia.org/browse/CCM-103
=> CCM-103: Add one-shot package to handle peculiar Jahia redeploy

mixins/common.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1865
=> PAAS-1865: Add check to unmute after monitor status is OK

packages/jahia/link-to-jcustomer.yml, packages/jahia/migrations/migrate-to-v11.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1887
=> PAAS-1887: Update jExperience to 1.11.7 for Jahia 7.3 envs

packages/one-shot/paas-1915-fix-log4j-security-issue.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1915
=> PAAS-1915: one shot package to fix log4j security issue

packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1740
=> PAAS-1740: fix wrong indent in jahia update-envents package

packages/common/restore.yml, packages/jahia/migrations/migrate-to-v11.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1892
=> PAAS-1892: preserve jahia.session.jvmRoute param after a restore

packages/jahia/migrations/migrate-to-v11.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1892
=> PAAS-1892: fix wrong action name in migration package

packages/common/update-datadog-agent.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1919
=> PAAS-1919: add package to update datadog agent on all nodes

packages/jcustomer/migrations/migrate-to-v10.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1920
=> PAAS-1920: Add action to remove jahia_cfg_operatingMode from jCustomer envs' nodes

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1737
=> PAAS-1737 fix some conditionals, always set variable even if false

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1737
=> PAAS-1737 more console logs and always put back the inital conf if jexperience was active

packages/jahia/migrations/migrate-to-v11.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1887
=> PAAS-1887: Fix jExperience module upgrade only if already present

packages/jcustomer/migrations/migrate-to-v10.yaml, packages/jcustomer/migrations/v10_assets/dd_jmx_unomi_conf.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1929
=> PAAS-1929 interpret error stack as one line

packages/jcustomer/migrations/migrate-to-v10.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1929
=> PAAS-1929 add missing dd agent restart

assets/common/hn_infos.py, assets/common/hn_nodes_list.py
JIRA issue: https://jira.jahia.org/browse/PAAS-1902
=> PAAS-1902: add script to get infos on running nodes on a hardware_node

packages/one-shot/paas-1937-jahia-macros-patch-security-issue.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1937
=> PAAS-1937 upgrade Jahia Macros module (security issue)

packages/one-shot/paas-1875-upgrade-distributed-sessions.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1875
=> PAAS-1875 uninstall old distributed-sessions at cluster level

packages/one-shot/paas-1875-upgrade-distributed-sessions.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1875
=> PAAS-1875 fix typo

packages/one-shot/paas-1875-upgrade-distributed-sessions.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1875
=> PAAS-1875 ensure new DS is started at cluster level

packages/one-shot/paas-1875-upgrade-distributed-sessions.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1875
=> PAAS-1875 handle not expected cases

assets/common/hn_upgrade.py
JIRA issue: https://jira.jahia.org/browse/PAAS-1938
=> PAAS-1938 replay start/start nodes error(s) on exit

packages/one-shot/paas-1934-dd-key-rotation.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1934
=> PAAS-1934: One-shot package to import new DD RPM key

packages/jahia/migrations/migrate-to-v12.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1930
=> PAAS-1930: Add migration action to fix tomcat logs parsing issue with GC logs

packages/jahia/migrations/migrate-to-v12.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1945
=> PAAS-1945: Add migration action to remove old mail lib when needed

packages/jahia/migrations/migrate-to-v12.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1945
=> PAAS-1945: also remove lib in /data folder

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v12.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1954
=> PAAS-1954: update jahia_cfg_mvnPath during onAfterRedeploy

packages/one-shot/paas-1875-upgrade-distributed-sessions.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1955
=> PAAS-1955: fix DS module install in oneshot package

packages/jahia/migrations/migrate-to-v12.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1954
=> PAAS-1954: fix missing dollar sign for variable

mixins/elasticsearch.yml, packages/common/backup.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1909
=> PAAS-1909: Update backup/restore for EC deployments

mixins/elasticsearch.yml, mixins/jcustomer.yml, packages/jcustomer/install.yml
:warning: to be merged along with https://github.com/Jahia/jahia-cloud-modules/pull/487 (otherwise env creation will be broken)
=> PAAS-1854: handle EC deployment at jcustomer env creation

packages/jcustomer/install.yml
=> PAAS-1854: fix shortdomain variable

packages/jahia/install.yml, packages/jcustomer/install.yml
=> PAAS-1854: add explicit comments about shortdomain setting

mixins/elasticsearch.yml, packages/common/backup.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1909
=> PAAS-1909: use EC admin user to backup/restore

packages/common/backup.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1909
=> PAAS-1909: fix ES restore rename_pattern regex and exclude geoname

mixins/elasticsearch.yml, packages/jcustomer/update-events.yml
=> PAAS-1854: code cleanup to remove unused actions related to ES nodes

mixins/elasticsearch.yml, packages/common/backup.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1909
=> Paas 1909 backup restore ec

packages/one-shot/paas-1971-fix-macros-ds-locations.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1971
=> PAAS-1971: One-shot package to fix Macros and DS modules location

packages/one-shot/paas-1971-fix-macros-ds-locations.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1971
Fix provided by Thomas. Still works with Jahia 8.
=> PAAS-1971: Fix paas-1971-fix-macros-ds-locations package for Jahia 7

packages/one-shot/paas-1962-apply-8032-patch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1962
=> PAAS-1962: One-shot package to apply 8.0.3.2 patch

packages/one-shot/paas-1962-apply-8032-patch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1962
=> PAAS-1962: Fix Jahia version check

packages/one-shot/paas-1982-fix-jessionid.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1982
=> PAAS-1982: add package to fix jsessionid on jahia 8.1.1.0

packages/one-shot/paas-1982-fix-jessionid.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1982
=> PAAS-1982: fix action name

packages/one-shot/paas-1982-fix-jessionid.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1982
=> PAAS-1982: fix is now idempotent

mixins/elasticsearch.yml
remaining. Otherwise, remove env indices
JIRA issue: https://jira.jahia.org/browse/PAAS-1980
=> PAAS-1980: delete ec_deployment if there is no jcustomer env linked

packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v11.yaml, packages/jcustomer/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1992
=> PAAS-1992: configure shards and replicas

packages/jcustomer/migrations/migrate-to-v11.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1992
=> PAAS-1992: make configureShardsAndReplicas idempotent

packages/jcustomer/migrations/migrate-to-v11.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1992
=> PAAS-1992: fix sed parameters

mixins/elasticsearch.yml, packages/common/restore.yml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v11.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2003
=> PAAS-2003: Double underscore in ES index prefix

mixins/elasticsearch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1989
=> PAAS-1989: Skip timeout when updating EC deployment

packages/jcustomer/migrations/migrate-to-v11.yaml, packages/jcustomer/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1977
=> Paas 1977 jcustomer duplicate events

mixins/elasticsearch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1989
=> PAAS-1989: Fix the check condition

packages/jahia/ipsec.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2009
=> PAAS-2009: fix subnets overlapping check

packages/jcustomer/migrations/migrate-to-v11.yaml
=> PAAS-1970 check if backup and restore are done before doing them

packages/jcustomer/migrations/migrate-to-v11.yaml
=> PAAS-1970: fix wrong cmd target

packages/jcustomer/migrations/migrate-to-v11.yaml
=> PAAS-1970 fix FRO launched on not started jahia env

packages/jcustomer/migrations/migrate-to-v11.yaml
=> PAAS-1970 fix missing multiline block indicator

packages/jcustomer/migrations/migrate-to-v11.yaml
=> PAAS-1970: Fix EcDeployment name for prod envs

mixins/elasticsearch.yml, packages/common/backup.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2012
=> PAAS-2012: handle ES backup backward compatibility

mixins/elasticsearch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1999
=> PAAS-1999 fix nodegroupdata grab from the wrong nodegroup

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2012
=> PAAS-2012: add jcustomer healthcheck after legacy restore

packages/one-shot/paas-2018-spring4shell-mitigation.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2018
=> PAAS-2018: spring4shell mitigation patch

mixins/elasticsearch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2019
=> PAAS-2019: don't wait 20m if no workflow created

mixins/elasticsearch.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2020
=> PAAS-2020: improve consistency the ES restore

mixins/elasticsearch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2019
=> PAAS-2019: fail if no workflow only once

mixins/jahia.yml, packages/common/restore.yml, packages/jahia/update-events.yml, packages/one-shot/paas-2026-clean-jr-r-local-revisions-table.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2026
=> PAAS-2026: clean JR_J_LOCAL_REVISIONS table

packages/jcustomer/migrations/v11_assets/restore_for_ec_migration.yml, packages/one-shot/paas-2029-fix-analyser-missing-in-indices-after-ec-migration.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2029
=> PAAS-2029 fix indices without analyser

packages/jahia/migrations/migrate-to-v13.yaml
=> PAAS-1786: fix pat and sam version installed for jahia 8.0.3.0

packages/jahia/ipsec.yml, packages/jahia/migrations/v7_assets/ipsec_updown.sh
JIRA issue: https://jira.jahia.org/browse/PAAS-2032
=> PAAS-2032: fix ipsec package bugs

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v13.yaml, packages/jahia/migrations/migrate-to-v14.yaml
I also incremented jahia_env_version following hotfix v1.8.1
=> PAAS-1786: Update PAT version to v1.0.1 for Jahia 8.0 

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2026
=> PAAS-2026: Fix cleanJRJJournalTable action

mixins/mariadb.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2040
=> PAAS-2040: check for mariabackup process when starting MariaDB

packages/jahia/migrations/migrate-to-v14.yaml
=> PAAS-1786: Check that module state did not change during PAT and SAM

conf/preprod.conf.json, conf/prod.conf.json
JIRA issue: https://jira.jahia.org/browse/PAAS-2042
=> PAAS-2042: Use new 'major' tag for ec-infra

mixins/elasticsearch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2042
=> PAAS-2042: Adapt git tag regex so that it works with new 'v1' tag

packages/jahia/migrations/migrate-to-v14.yaml
=> PAAS-1786: Fix migration for Jahia 8.0.3

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2039
=> PAAS-2039: handle PAT token during backup restore

packages/jahia/migrations/migrate-to-v14.yaml
=> Paas 1786 stupid fixes

packages/jcustomer/reindexation.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2047
=> PAAS-2047 add jCustomer reindexation manifest

mixins/jahia.yml, packages/common/restore.yml, packages/jahia/install.yml
=> PAAS-1786: rename pat.groovy again so it's executed after modules starts

packages/jcustomer/install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2042
=> PAAS-2042: Update jcustomer_env_version in install package

mixins/haproxy.yml, mixins/jahia.yml, mixins/jcustomer.yml, mixins/mariadb.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v15.yaml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v13.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1543
=> PAAS-1543 Re-enable io check in datadog agent

packages/jcustomer/migrations/migrate-to-v13.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1543
=> PAAS-1543 add missing dependices to mixins/jcustomer.yml

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v15.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2044
=> PAAS-2044: Add datadog APM opts to fix forms issue

packages/jahia/migrations/migrate-to-v15.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2044
=> PAAS-2044: Fix migration package

packages/common/backup.yml, packages/common/restore.yml, packages/jahia/migrations/migrate-to-v15.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2038
=> PAAS-2038: Stop backing up and restoring jahia_cfg_mvnPath envvar

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2046
=> PAAS-2046: Fix wrong number of shards if needed

packages/one-shot/paas-2052-remove-es-nodes.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2052
=> PAAS-2052: Add one-shot package to remove es nodes from jCustomer envs

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2045
=> PAAS-2045 recreate trigger(s) after a restore

assets/haproxy/haproxy-jahia-cloud.cfg, packages/jahia/migrations/migrate-to-v15.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2070
=> PAAS-2070 Use CRLF for haproxy's httpchk headers

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2077
=> PAAS-2077: Clean up patches folder before creating new pat.groovy script

mixins/jahia.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2043
=> PAAS-2043: test clearing revisions

mixins/elasticsearch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2060
=> PAAS-2060: Fix issue with snapshot repository for ES backup on Azure

mixins/elasticsearch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2063
=> PAAS-2063: Clean up geonameentry alias on env delete

packages/jahia/migrations/migrate-to-v15.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1984
=> PAAS-1984: Revert JSESSIONID patch for 8.1.1

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1916
=> PAAS-1916: fix if condition checking module state in checkModuleAction

packages/jahia/link-to-jcustomer.yml, packages/jahia/migrations/migrate-to-v15.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2061
=> PAAS-2061: upgrade jexperience for 7.3 and 8.1

mixins/jahia.yml, packages/jahia/manage-module.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1916
=> PAAS-1916: improve wording for manage-module package and fix uninstallModule action only removing last version

packages/jahia/link-to-jcustomer.yml, packages/jahia/manage-module.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1916
=> Paas 1916 manage modules with jahia api

mixins/jahia.yml, packages/one-shot/paas-2006-migrate-as-environments-to-elastic-cloud.yml
elastic cloud
JIRA issue: https://jira.jahia.org/browse/PAAS-2006
=> PAAS-2006: One shot package to migrate augmented search environments to

mixins/elasticsearch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1855
=> PAAS-1855: update AS indices pattern when creating kibana role

mixins/elasticsearch.yml, mixins/jahia.yml, packages/jahia/update-events.yml
environment having augmented search
JIRA issue: https://jira.jahia.org/browse/PAAS-1998
=> PAAS-1998: handle EC deployment deletion when deleting a jahia

packages/jahia/migrations/migrate-to-v16.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2089
=> PAAS-2089: Fix typos in migration package

mixins/common.yml, packages/common/restore.yml, packages/jahia/update-events.yml, packages/jahia/upgrade.yml
stop/start/delete/restore/upgrade
JIRA issue: https://jira.jahia.org/browse/PAAS-2001
=> PAAS-2001: handle muting of envname based monitors at

packages/jahia/augmented-search-uninstall.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1997
=> PAAS-1997: add AS uninstall package

packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-954
=> PAAS-954: Clean journal table on environment or processing node restart

packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-954
=> PAAS-954: Only clean journal table on proc restart

mixins/jcustomer.yml, packages/jcustomer/migrations/migrate-to-v14.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2022
=> Paas 2022 dd apm j customer

packages/jahia/migrations/migrate-to-v16.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2057
=> PAAS-2057: Fix DATADOG_APM_ENABLED envvar update in migration package

mixins/elasticsearch.yml, mixins/jahia.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1960
=> PAAS-1960: Handle Augmented search module at backup restore

mixins/jahia.yml, mixins/jcustomer.yml, packages/jcustomer/migrations/migrate-to-v14.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2022
=> PAAS-2022: fix default value for variable because of Cloudscripting

packages/one-shot/paas-2006-migrate-as-environments-to-elastic-cloud.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2110
=> PAAS-2110: handle PIM connector for AS migration

packages/common/backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2111
=> PAAS-2111: fix tar not saving full timestamp during backup

packages/one-shot/paas-2006-migrate-as-environments-to-elastic-cloud.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2110
=> PAAS-2110 fix sed command, better regex, cleaner

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1960
=> PAAS-1960: fix space before colon

mixins/common.yml, mixins/jcustomer.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v16.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1997
=> PAAS-1997: add JEL_ENV_ROLE to Jahia envs to fix AS uninstall package

packages/jahia/migrations/migrate-to-v16.yaml, packages/jahia/migrations/v16_assets/strongswan_connections_status.py
JIRA issue: https://jira.jahia.org/browse/COPS-579
=> COPS-579 update env with new strongswan check version

packages/jahia/augmented-search-install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1855
=> PAAS-1855 Create Augmented Search install package

packages/jahia/augmented-search-install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1855
=> fix bad test

mixins/jahia.yml, mixins/jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1988
=> PAAS-1988: Fix usage of wrong data in mixins and packages

packages/jahia/augmented-search-install.yml, packages/one-shot/paas-2006-migrate-as-environments-to-elastic-cloud.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2121
=> PAAS-2121: Bump AS to 1.6.1 / 3.3.1

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2106
=> PAAS-2106: Update EC score/topology before restore if needed

mixins/jahia.yml, packages/jahia/augmented-search-install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1855
=> PAAS-1855: Update jahia-administration to 1.5.0 when installing AS for Jahia 8.1.0

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2106
=> PAAS-2106: Add missing quotes for curl requests

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2106
=> PAAS-2106: Fix EOF indentation

packages/jahia/augmented-search-install.yml, packages/one-shot/paas-2006-migrate-as-environments-to-elastic-cloud.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2124
=> PAAS-2124: Bump installed versions of AS to 1.6.2/3.3.2

mixins/jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1991
=> PAAS-1991: Remove useless actions in updateHazelcast

packages/jahia/migrations/migrate-to-v16.yaml
JIRA issue: https://jira.jahia.org/browse/CCM-128
=> CCM-128: Fix migration package Jahia v16

packages/one-shot/fix-es-prefix-env-var.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-XXX
=> Fix es prefix

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2076
=> PAAS-2076: Use reindex flag instead of purging index and workspace folders

mixins/jahia.yml, packages/jahia/jahia-rolling-redeploy.yml, packages/jahia/upgrade.yml, packages/jcustomer/jcustomer-rolling-redeploy.yml, packages/jcustomer/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1830
I also changed the way the rolling redeploy works for jCustomer. Actually, it was not rolling, so I made it roll :)
=> PAAS-1830: Split upgrade and rolling-redeploy into distinct packages

mixins/haproxy.yml, mixins/jahia.yml, mixins/mariadb.yml, packages/jahia/migrations/migrate-to-v17.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2062
=> PAAS-2062: Replace 'service' value in DD config with source instead of envname

mixins/common.yml, packages/common/update-datadog-agent.yml, packages/jahia/ipsec.yml, packages/jahia/migrations/migrate-to-v17.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2139
=> Paas 2139 dd agent json

README.md, deps.py, deps_requirements.txt
JIRA issue: https://jira.jahia.org/browse/PAAS-2122
=> PAAS-2122 add dependencies check script

packages/jahia/migrations/v17_assets/augmented_search.py
JIRA issue: https://jira.jahia.org/browse/PAAS-2114
=> PAAS-2114: improve dd check messages when AS module is not running

mixins/jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2140
=> PAAS-2140: remove duplicate setJournaldLimit action

mixins/jahia.yml, packages/jahia/consistency-check.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2125
=> PAAS-2125: New jahia-consistency-check package to check modules state

packages/jahia/jahia-rolling-redeploy.yml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v15.yaml, packages/jcustomer/update-events.yml, packages/jcustomer/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2126
=> PAAS-2126: Mute env-wide monitors on jCustomer stop/delete/upgrade

mixins/common.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2126
=> PAAS-2126: Use first cp instead of proc node for 'common' actions

packages/jcustomer/migrations/migrate-to-v15.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2126
=> PAAS-2126: Fix migration package name and id

mixins/common.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2030
=> PAAS-2030: Add the missing ':'

mixins/common.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2142
=> PAAS-2142 add exit 0 on muteDatadogHost

assets/haproxy/haproxy-jahia-cloud.cfg, assets/haproxy/haproxy_prestart.sh, assets/haproxy/http-errors.cfg, mixins/haproxy.yml, packages/common/backup.yml, packages/common/restore.yml, packages/jahia/migrations/migrate-to-v17.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1094
=> PAAS-1094: handle haproxy custom error pages

mixins/common.yml, mixins/jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2030
=> Paas 2030 fixes

mixins/common.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2030
=> PAAS-2030: Fix Vault secrets deletion

mixins/elasticsearch.yml, packages/common/backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2030
=> PAAS-2030: Fix Elasticsearch backup

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2133
=> PAAS-2133: Fix cleanJRLocalRevisionsTable action to run on db nodes

packages/jahia/migrations/migrate-to-v17.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1094
=> PAAS-1094: fix haproxy reload in migration to v17

mixins/jcustomer.yml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v15.yaml, packages/jcustomer/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2145
=> PAAS-2145 fix redeploy/upgrade breaking APM, set apm in setenv before restart karaf on install

packages/jahia/consistency-check.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v18.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2131
=> PAAS-2131 bump to SAM 2.2.0 for jahia 8.1.2+

packages/jahia/consistency-check.yml, packages/jahia/migrations/migrate-to-v18.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2144
=> Paas 2144 pat120

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v18.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2132
=> PAAS-2132: Increase jdbc maxAge setting from 5min to 15min

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2149
=> PAAS-2149: Hide globals secret as param from Jelastic action

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2149
=> PAAS-2149: Add the missing _ from the setupDatadogAgentJahia action

packages/common/backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2127
=> PAAS-2127: make sure ES snapshot is successful before exiting

assets/common/backrest.py, assets/common/papi.py, assets/elasticsearch/elasticsearch.py, mixins/common.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v18.yaml, packages/jahia/update-events.yml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v15.yaml, packages/jcustomer/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2028
=> Paas 2028 upgrade python

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2084
=> PAAS-2084: Fix Jahia upgrade from v7 to v8 for Screeb module

packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v15.yaml, packages/jcustomer/migrations/migrate-to-v16.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2028
=> PAAS-2028: move upgradePython action to new migraion-v16 package

mixins/common.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2028
=> PAAS-2028: Add check before installing Python in case it already is

assets/haproxy/haproxy-jahia-cloud.cfg, packages/jahia/migrations/migrate-to-v18.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2071
=> PAAS-2071: Capture full X-Forwarded-For header in HAProxy

mixins/jahia.yml, packages/jahia/link-to-jcustomer.yml, packages/jcustomer/get-kibana-endpoint.yml, packages/jcustomer/reset-kibana-admin-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2096
=> PAAS-2096: fix SSO for Kibana-dashboard conf and returns Kibana endpoint with admin credentials

mixins/jahia.yml, packages/jahia/link-to-jcustomer.yml, packages/jahia/migrations/migrate-to-v18.yaml, packages/jcustomer/reset-password-of-customer-kibana-user.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2096
=> PAAS-2096: change the customer's Kibana user name from admin to user

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2105
=> PAAS-2105: Fix backup restore for screeb and kibana dashboard configs

packages/common/restore.yml, packages/jahia/migrations/migrate-to-v18.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2132
=> PAAS-2132 disable removeAbandoned on restore and incrase removeAbandonedTimeout instead of maxAge

assets/database/mysql.cnf, mixins/mariadb.yml, packages/jahia/migrations/migrate-to-v18.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1944
=> PAAS-1944 Force performance_schema_session_connect_attrs_size = -1 in mariadb daemon

assets/database/mysql.cnf, packages/jahia/migrations/migrate-to-v18.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2156
=> PAAS-2156 set max_connections=360

mixins/jahia.yml, packages/jahia/link-to-jcustomer.yml, packages/jahia/migrations/migrate-to-v18.yaml, packages/jahia/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2147
=> PAAS-2147: install and configure kibana-dashboard-provider if upgrading from Jahia 7 to Jahia 8

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2151
=> PAAS-2151: check if module started after installation, refactor checkModule action

packages/jahia/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2147
=> PAAS-2147: fix Jahia 7 test in upgrade package

assets/haproxy/haproxy-reload.sh, packages/jahia/migrations/migrate-to-v18.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2157
=> PAAS-2157 fix haproxy conf check not in stdout

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2151
=> PAAS-2151: fix and improve the check of module startup after installation

packages/jahia/unlink-jahia-jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2064
=> PAAS-2064: fix unlink package if isUnomiEnvDeletion setting is not provided

mixins/jahia.yml, packages/jahia/link-to-jcustomer.yml, packages/jahia/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2159
=> PAAS-2159: upgrade jExperience if needed when upgrading Jahia

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2147
=> PAAS-2147: define repoRootUrl before trying to setup Kibana Dashboard

packages/jahia/migrations/migrate-to-v18.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2144
=> PAAS-2144: Do not upgrade PAT for Jahia 8.1.1.0

packages/jahia/migrations/migrate-to-v18.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2084
=> PAAS-2084: Do not install Screeb module for Jahia 8.0

mixins/common.yml, mixins/elasticsearch.yml, mixins/jahia.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2163
=> Paas 2163 fix papitoken global

packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v17.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1974
=> PAAS-1974: add JVM parameters to jcustomer process

packages/jcustomer/migrations/migrate-to-v17.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2167
=> PAAS-2167: Redeploy jCustomer envs to upgrade JDK to v11

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v19.yaml, packages/jahia/migrations/v19_assets/thread-dump.sh
JIRA issue: https://jira.jahia.org/browse/PAAS-2158
=> PAAS-2158: update thread-dump.sh script in migration package

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1834
=> PAAS-1834: clean unused and duplicated directories

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1834
=> PAAS-1834: fix /opt/tomcat/webapps folder copy

mixins/common.yml, mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2138
=> PAAS-2138: improve checkDatadogAgentCheck by checking monitors status

packages/jahia/migrations/migrate-to-v19.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1528
=> PAAS-1528: Switch the log4j logger org.jahia.bin.errors to INFO

mixins/mariadb.yml, packages/jahia/migrations/migrate-to-v19.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2178
=> PAAS-2178: set replication and galera_cluster to false in dd conf for single nodes

packages/jahia/migrations/migrate-to-v19.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2166
=> PAAS-2166 set DocId log level to error

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2169
=> PAAS-2169 on DB restore, stop the mysql daemon no matter what

packages/jahia/reset-pat-token.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2171
=> PAAS-2171: Add jahia-reset-pat-token package

mixins/elasticsearch.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2188
It's sad, but it works...
=> PAAS-2188: Add 1 sec delay to wait for CCI pipeline to really be created

assets/common/set_dd_tags_cron, packages/jahia/migrations/migrate-to-v19.yaml, packages/jcustomer/migrations/migrate-to-v17.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2069
=> PAAS-2069: disable mail notifications for set_dd_tags_cron execution

mixins/jahia.yml, packages/jahia/consistency-check.yml, packages/jahia/migrations/migrate-to-v19.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2186
=> PAAS-2186 bump jexperience version to 1.11.9 for jahia 7 envs

packages/jahia/augmented-search-install.yml, packages/jahia/consistency-check.yml, packages/jahia/migrations/migrate-to-v19.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2185
=> PAAS-2185: update augmentedsearch to 3.3.3

packages/common/restore.yml, packages/jahia/reset-pat-token.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2196
=> Paas 2196 reset pat token

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2196
=> PAAS-2196: Fix PAT groovy script in restore

packages/jahia/reset-pat-token.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2196
=> PAAS-2196: Restart haproxy service to take new token into account

packages/jahia/migrations/migrate-to-v19.yaml, packages/jahia/migrations/v19_assets/org.ops4j.pax.url.mvn.cfg
JIRA issue: https://jira.jahia.org/browse/PAAS-2197
=> PAAS-2197: fix jahia config file for Maven

assets/haproxy/haproxy-jahia-cloud.cfg, packages/jahia/migrations/migrate-to-v19.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2203
=> PAAS-2203: reset haproxy log-format to default for Datadog parsing

packages/jahia/migrations/migrate-to-v19.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2203
=> PAAS-2203: fix sed in resetHaproxyLogFormat action

mixins/jahia.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v20.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2199
=> PAAS-2199 switch to G1GC algorithm

mixins/jahia.yml, mixins/mariadb.yml, packages/jahia/migrations/migrate-to-v20.yaml, packages/jahia/migrations/v20_assets/jahia_local_revisions_discrepancies.py, packages/jahia/migrations/v20_assets/jahia_local_revisions_discrepancies.yaml, packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2175
=> PAAS-2175 add local revisions custom check

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2209
=> PAAS-2209 use ignoreChecks on module installation

packages/one-shot/paas-2218-patch-shiro-1-10.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2218
=> PAAS-2218: New one-shot package to patch shiro lib

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1681
=> PAAS-1681: fix mv of applicationcontext-purge-jobs file in restore

mixins/jahia.yml, packages/jahia/jahia-rolling-redeploy.yml, packages/jahia/rolling-upgrade.yml, packages/jahia/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2212
=> PAAS-2212: Add new jahia-rolling-upgrade package

packages/common/restore.yml, packages/jahia/migrations/migrate-to-v20.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1681
=> PAAS-1681: move mv of applicationcontext-purge-jobs after cfg restore in restore package

packages/common/restore.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v20.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2175
=> PAAS-2175 fix restore, better migration (on cp too)

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2211
=> PAAS-2211 add loop until jahia.log is created in startupJahiaHealthCheck

packages/jahia/consistency-check.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2222
=> PAAS-2222: Update jahia-consistency-check regarding DS 3.4.0

packages/jahia/consistency-check.yml, packages/jahia/migrations/migrate-to-v20.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2224
=> PAAS-2224: upgrade SAM to 2.3.0 for jahia 8.1.2.0+

packages/jahia/migrations/migrate-to-v20.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2194
=> PAAS-2194: Fix the missing underscore from the var name

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v20.yaml, packages/jahia/migrations/v20_assets/thread-dump.sh
JIRA issue: https://jira.jahia.org/browse/PAAS-2220
Better to merge https://github.com/Jahia/jahiastic-jahia/pull/243 first
=> PAAS-2220: move heap/thread dumps to different folder

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v20.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2220
=> PAAS-2220: fix HeapDumpPath in JAVA_OPTS

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v20.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2194
=> PAAS-2194: Handle pat special characters in sed replace

packages/jahia/migrations/migrate-to-v20.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2220
=> PAAS-2220: fix non-working sed in moveDumpsToDifferentFolder

packages/one-shot/paas-2237-fix-pax-url-mvn.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2237
=> PAAS-2237: Add jahia-fix-pax-url-mvn one-shot package

packages/jahia/rolling-upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2212
=> PAAS-2212: Do not mute synthetic check during rolling upgrade

assets/jahia/as-restore-modules-provisioning-file.yaml, assets/jahia/jcustomer-restore-module-provisioning-file.yaml, packages/common/restore.yml
* A bit of renaming for more clarity
* I removed the newJexperienceStatus since it doesn't really bring anything
* I removed the stop of Augmented Search before upgrade for Jahia 7 because I believe that it's useless, I tested without and it works fine
=> PAAS-2217: fix AS restore for Jahia 7 if module not present

packages/common/restore.yml
=> Paas 2217 improve restore

packages/jahia/migrations/migrate-to-v20.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2223
=> PAAS-2223: Only upgrade Distributed Sessions when already started

packages/common/restore.yml
=> PAAS-2217: fix permission issue when moving kibana-dashboards conf file during restore

packages/common/restore.yml
=> PAAS-2217: remove test with variable that doesn't exist anymore

packages/jcustomer/set-unomi-root-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2244
=> PAAS-2244: fix jcustomer password to update in Jahia broken since secrets masking

README.md, mixins/elasticsearch.yml, mixins/jcustomer.yml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v18.yaml, packages/jcustomer/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2240
=> PAAS-2240: Refactor onAfterRedeployContainer

mixins/jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2240
=> PAAS-2240: Fix setupUnomi output when enabling karaf

packages/jcustomer/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2240
=> PAAS-2240: Fix jCustomer upgrade

mixins/jcustomer.yml, packages/jcustomer/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2240
=> PAAS-2240: Fix Datadog config update on redeploy and scale-out

packages/common/backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2249
=> PAAS-2249: Rotate jCustomer envvars backups

packages/one-shot/switch-from-g1gc-to-parallelgc.yml
JIRA issue: https://jira.jahia.org/browse/CCM-145
=> CCM-145: Revert to ParallelGC

mixins/jahia.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v21.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2259
=> PAAS-2259: Restore ParallelGC

packages/jahia/migrations/migrate-to-v21.yaml, packages/jahia/migrations/v21_assets/thread-dump.sh
JIRA issue: https://jira.jahia.org/browse/PAAS-2255
=> PAAS-2255: Fix thread dumps rotation and clean up

packages/jahia/migrations/migrate-to-v21.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2255
=> PAAS-2255: Fix clean-up of undeleted folders

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2247
=> PAAS-2247 increase shards ratio to 100 for any kind of mutualized EC

packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1885
=> PAAS-1885: add stop tomcat command in onBeforeScaleIn event

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1885
=> PAAS-1885: fix wrong quote when setting APM_OPTS

packages/common/auto_backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2250
=> PAAS-2250: Add onAfterRedeployContainer event for autobackup container

packages/jcustomer/geolite-database-update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2229
=> PAAS-2229: Fix the nodeId parameter for node restart

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v22.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2200
=> PAAS-2200 increase Jahia's logs max line length

packages/common/restore.yml, packages/jahia/migrations/migrate-to-v22.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2265
=> PAAS-2265: update JDBC configuration to avoid breaking long connections

packages/jahia/augmented-search-install.yml, packages/jahia/consistency-check.yml, packages/jahia/migrations/migrate-to-v22.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2267
=> PAAS-2267 bump AS version to 1.7.0 for jahia7 and to 3.4.0 for jahia>8.1

packages/common/backup.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-692
=> COPS-692: fix auth basic state at restore

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v22.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2265
=> PAAS-2265: increase proxySQL max_connections to 100 to match jdbc limit

packages/jcustomer/maxmind-key-update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2275
=> PAAS-2275: Package to update maxmind key on jCustomer environments

assets/common/rclone-cron, assets/common/rclone-logs.sh, assets/common/rclone.conf, assets/haproxy/logrotate_haproxy, mixins/common.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v22.yaml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v19.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2193
=> PAAS-2193: Handle s3 buckets to store logs

packages/jahia/consistency-check.yml, packages/jahia/migrations/migrate-to-v22.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2268
=> Paas 2268 graphql 2 16

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2277
=> PAAS-2277: remove remaining files after haproxy restore

packages/jahia/augmented-search-install.yml, packages/jahia/consistency-check.yml, packages/jahia/migrations/migrate-to-v22.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2267
=> PAAS-2267 bump AS v3.4.0 to v3.4.1

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v22.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2279
=> PAAS-2279: Force the JVM to use /dev/urandom to prevent entropy issues

packages/jahia/consistency-check.yml, packages/jahia/migrations/migrate-to-v22.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2276
=> PAAS-2276: Upgrade SAM to 2.4.0 for Jahia 8.1.2+

packages/one-shot/PAAS-2287-apply-8131-patch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2287
=> PAAS-2287: Add one-shot package to apply Jahia 8.1.3.1 patch

assets/common/backrest.py, assets/common/rclone.conf, mixins/common.yml, packages/common/backup.yml, packages/common/restore.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v22.yaml, packages/jcustomer/install.yml
=> PAAS-2266: use rclone to sync backup files with S3 buckets

packages/jahia/migrations/migrate-to-v22.yaml, packages/jcustomer/migrations/migrate-to-v19.yaml
=> PAAS-2266: Fix action name in jcustomer migration package for s3bucket

mixins/common.yml, packages/common/restore.yml
=> PAAS-2266: fix bucket name issue for legacy ovh backups

assets/common/papi.py, assets/common/rclone.conf, mixins/common.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2288
=> PAAS-2288: send logs to OVH as well

mixins/common.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2288
=> PAAS-2288: correct Papi endpoint to get organizations' secrets

mixins/common.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2288
=> PAAS-2288: fix OVH region to GRA for logs archiving

mixins/common.yml
=> PAAS-2266: fix ovh legacy backup bucket name (again...)

assets/database/check_galera_wsrep_ready_status.py, assets/haproxy/dd_agent_haproxy_conf.yml, assets/haproxy/haproxy_one_remaining_browsing.py, mixins/common.yml, mixins/haproxy.yml, mixins/mariadb.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v23.yaml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v20.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2270
=> PAAS-2270 bump to dd agent v7

packages/common/backup.yml
=> PAAS-2266: fix backup to purge in metadata when rotating backups

packages/jahia/migrations/migrate-to-v23.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2270
=> PAAS-2270: fix typo in migration package

packages/jahia/augmented-search-install.yml, packages/jahia/migrations/migrate-to-v23.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2264
=> Paas 2264 AS config

packages/jahia/augmented-search-install.yml, packages/jahia/consistency-check.yml, packages/jahia/migrations/migrate-to-v23.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2302
=> PAAS-2302 upgrade augmented search to 3.4.2

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v23.yaml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v20.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2285
=> Paas 2285 remove hn label

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2308
=> PAAS-2308 add fallback method to action checkModule

packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v20.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1403
Short description: Change Unomi nodeGroup displayName in jcustomer install package & next migration package
=> PAAS-1403: change jCustomer nodeGroup displayName

packages/common/backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2311
=> PAAS-2311 add a lock to backup's metadata file before updating it

packages/jahia/migrations/migrate-to-v23.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2310
=> PAAS-2310: add whitelist for SAM module

assets/haproxy/haproxy-jahia-cloud.cfg, assets/haproxy/robots_noindex.txt, mixins/haproxy.yml, packages/jahia/migrations/migrate-to-v23.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2309
=> PAAS-2309: Update HAProxy config to not index technical domains

packages/one-shot/paas-2322-upgrade-to-dx-clustering-8107.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2322
=> PAAS-2322 fix secret password not masked when adding the repo

packages/jahia/unlink-jahia-jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2315
Add the removeKibanaDashboardAccountsAndSpace action to make sure everything kibana related is deleted when unlinking.
=> PAAS-2315: fix Jahia jCustomer unlink issue

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v24.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2332
Short description: add v24 migration package & remove info from error page
=> PAAS-2332: remove info from error page

mixins/jahia.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v24.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2331
=> PAAS-2331: randomize proxysql credentials

packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v21.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2317
Short description: fix the action order to make sure APM_OPTS are used in jCustomer. Add a migration package to fix this issue.
=> PAAS-2317: fix Datadog APM_OPTS in jCustomer environment

packages/common/backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2351
=> PAAS-2351: fix grep pattern in rotate backup action

assets/common/sudoers-file, mixins/common.yml, mixins/haproxy.yml, mixins/jahia.yml, mixins/jcustomer.yml, mixins/mariadb.yml, packages/common/auto_backup.yml, packages/common/backup.yml, packages/common/restore.yml, packages/common/start-nodes.yaml, packages/common/stop-nodes.yaml, packages/jahia/augmented-search-install.yml, packages/jahia/augmented-search-uninstall.yml, packages/jahia/ipsec.yml, packages/jahia/migrations/migrate-to-v24.yaml, packages/jahia/migrations/v24_assets/sudoers-file, packages/jahia/perf-test-step1.yml, packages/jahia/perf-test-step2.yml, packages/jahia/reset-pat-token.yml, packages/jahia/rewrite-rules.yml, packages/jahia/set-jcustomer-password-in-jahia.yml, packages/jahia/update-events.yml, packages/jahia/upgrade.yml, packages/jcustomer/reindexation.yml, packages/jcustomer/upgrade.yml
The `jelastic` user is now linked to `root` so any `cmd` that doesn't have any user set will be run with `root`.
=> Paas 2330: remove sudo permissions

mixins/common.yml, mixins/haproxy.yml, mixins/jahia.yml, mixins/mariadb.yml, packages/common/backup.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v24.yaml, packages/jahia/update-events.yml
=> Paas 2330 remove sudo permissions

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v24.yaml, packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2331
=> PAAS-2331: fix proxysql credentials lost at browsing scaleout

packages/jahia/migrations/migrate-to-v24.yaml
=> PAAS-2330: fix migration package because of healthchecks not running as root anymore

mixins/common.yml
=> PAAS-2330: fix jCustomer scale out failing because of new bl nodes

mixins/common.yml
=> PAAS-2330: fix jcustomer scale out still not working because of new bl nodes

packages/common/backup.yml, packages/common/restore.yml
=> PAAS-2330: add missing user parameter for clearJelasticLogs action (my bad)

packages/jcustomer/reindexation.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2341
=> PAAS-2341 track reindex task instead of rely on wait_for_completion

packages/jahia/migrations/migrate-to-v25.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2219
Short description: Update tomcat & openjdk version to 9.0.71 & 11.0.18 respectively
=> PAAS-2219: update tomcat & openjdk

packages/one-shot/paas-2356-patch-findUser-vulnerability.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2356
=> PAAS-2356: create a one-shot package to patch the userFind vulnerability

packages/one-shot/paas-2356-patch-findUser-vulnerability.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2356
=> PAAS-2356: add missing mixin

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v25.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2363
=> PAAS-2363: fix and persit proxysql credentials

packages/jahia/migrations/migrate-to-v25.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2364
Short description: correct indentation error
=> PAAS-2364: correct indentation error

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2365
=> PAAS-2365 fix restore on galera envs

packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v22.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2355
=> PAAS-2355: use env vars to set XMX and XMS

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v26.yaml, packages/jcustomer/migrations/migrate-to-v22.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2362
=> PAAS-2362 add an option to bypass the chjecks on migrations packages

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v26.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2291
=> PAAS-2291: split nodes in AZs

packages/one-shot/paas-2322-upgrade-to-dx-clustering-8107.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2375
I don't understand why, but I need to do that so that the backslash is correctly added...
=> PAAS-2375: Fix backslash in config

packages/jahia/consistency-check.yml, packages/jahia/migrations/migrate-to-v26.yaml, packages/jahia/migrations/v26_assets/org.jahia.modules.modulemanager.configuration.constraints-cloud.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2321
Short description: disable operations on cloud managed modules
=> PAAS-2321: disable operations on cloud managed modules

README.md, packages/misc/setup-jahia-cloud-instance.yml
I tested it on https://development-jahiacloud.dev.j.jahia.com, it's working fine.
=> Add setup-jahia-cloud-instance package

packages/jahia/consistency-check.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2372
=> PAAS-2372: fix variable in consistency-check

packages/jahia/consistency-check.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2372
=> PAAS-2372: fix GraphQL version in consistency-check

mixins/haproxy.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v27.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2360
Short description: upgrade HAproxy to latest version
=> PAAS-2360: upgrade HAproxy to 2.7.8

mixins/haproxy.yml, packages/jahia/migrations/migrate-to-v27.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2360
=> PAAS-2360: fix haproxy redeploy

packages/jahia/migrations/migrate-to-v27.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2219
Short description: upgrade tomcat version to 9.0.75
=> PAAS-2219: upgrade tomcat to 9.0.75

packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v23.yaml, packages/jcustomer/migrations/v23_assets/karaf_override.lib
JIRA issue: https://jira.jahia.org/browse/PAAS-2393
=> PAAS-2393: prevent java autorestart in jcustomer

packages/common/backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2425
=> PAAS-2425 force region eu-west-1 when using rclone to read the lockfile

packages/jahia/migrations/migrate-to-v27.yaml, packages/jahia/migrations/v27_assets/jahia_override.lib
JIRA issue: https://jira.jahia.org/browse/PAAS-2253
=> PAAS-2253 add override for not restarting tomcat on cloudlet increase

mixins/jahia.yml, mixins/jcustomer.yml, packages/jahia/link-to-jcustomer.yml, packages/jahia/unlink-jahia-jcustomer.yml, packages/jahia/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2432
Short description: update jExperience installation actions to take into account jCustomer 2.0. Also update jExperience Dashboard installation actions accordingly.
=> PAAS-2432: adjust jExperience installation

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2445
Short description: Add a bundle refresh & restart for GraphQL and SAM as a last resort during startup.
=> PAAS-2445: fix bundle refresh issue

packages/common/backup.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2370
=> PAAS-2370: handle JCR index at backup/restore to make it faster

packages/jahia/migrations/v27_assets/jahia_override.lib, packages/jcustomer/migrations/v23_assets/karaf_override.lib
JIRA issue: https://jira.jahia.org/browse/PAAS-2474
=> PAAS-2474 fix envvar sourcing in override files

packages/one-shot/paas-2466-update-pax-web-jsp.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2466
=> PAAS-2466 add update pax-web-jsp one-shot package

assets/haproxy/haproxy-jahia-cloud.cfg, packages/jahia/migrations/migrate-to-v28.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2438
=> PAAS-2438: capture content-type header in Haproxy logs

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2491
=> PAAS-2491 add loop when switching FRO mode

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v28.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2495
=> PAAS-2495 Set tomcat's HOME as the service's working directory

packages/jahia/migrations/migrate-to-v29.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2478
=> PAAS-2478 fix sourcing envvars on override script

mixins/common.yml, packages/common/get_file_from_vault.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2387
=> PAAS-2389 add a manifest for creating file from a vault secret key value

assets/database/jahia_override.lib
JIRA issue: https://jira.jahia.org/browse/PAAS-2478
=> PAAS-2478 add missing updated override script

packages/jahia/migrations/migrate-to-v29.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2451
=> PAAS-2451: correct indentation mistake

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2509
=> PAAS-2509 force exit 0 after successfull 'until' loop

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2509
=> PAAS-2509 remove comments line from the end of the cmd block

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2513
=> PAAS-2513 bump jexperience to v2.7.2 for jahia 8.1+

packages/jahia/migrations/migrate-to-v29.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2471
=> PAAS-2471: patch ops4j.pax.web library

packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v24.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2368
Short description: adjust XMX on jCustomer envs depending on cloudlets number.
=> PAAS-2368: adjust jCustomer XMX

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v29.yaml, packages/jahia/migrations/v29_assets/proxysql_service_override
JIRA issue: https://jira.jahia.org/browse/PAAS-2516
=> PAAS-2516: fix ProxySQL startup error when logfile not present

packages/jahia/migrations/migrate-to-v29.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2516
=> PAAS-2516: run fixProxySQLStartup action on correct nodegroups

packages/common/backup.yml, packages/common/restore.yml, packages/jahia/migrations/migrate-to-v29.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2390
=> PAAS-2390: save provided list of custom conf files upon redeploy or backup/restore

packages/jahia/migrations/migrate-to-v29.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2390
=> PAAS-2390: add missing "fi" in fixProxySQLStartup

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v24.yaml, packages/jahia/migrations/migrate-to-v29.yaml, packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2516
=> PAAS-2516: fix proxySQL configuration when redeploying

packages/common/backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2390
=> PAAS-2390: fix and improve backup of custom conf files

packages/common/backup.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2390
=> PAAS-2390: remove backup of custom conf files

assets/common/check_before_hn_upgrade.py, assets/common/hn_nodes_list.py, packages/common/start-nodes.yaml, packages/common/stop-nodes.yaml, packages/jahia/install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2403
=> PAAS-2403: install the datastore on NFS/GlusterFS

packages/common/backup.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2423
=> COPS-2423 update backup/restore for datastore in filesystem

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v30.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2536
=> PAAS-2536: patch RMI security issue

packages/jahia/set-db-nodes-cloudlets.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2545
=> PAAS-2545: add package to set database nodes cloudlets

packages/jahia/set-db-nodes-cloudlets.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2545
=> PAAS-2545: fix db node restart in set-db-nodes-cloudlets package

mixins/jahia.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v31.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2549
Short description: 
- Modify _ROLE var for storage
- Add glusterFS log consumption configuration on client nodes
=> PAAS-2549: complete datadog storage setup

assets/common/backrest.py, mixins/common.yml, packages/common/backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2013
=> PAAS-2013: Add infos to backups metadata

assets/haproxy/haproxy-jahia-cloud.cfg, packages/jahia/migrations/migrate-to-v31.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2552
=> PAAS-2552: remove useless space in X-Forwarded-For header

packages/jahia/migrations/migrate-to-v31.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2557
=> PAAS-2557: fix sed in fixAPMMemoryLeak

packages/jahia/migrations/migrate-to-v31.yaml, packages/jahia/migrations/migrate-to-v32.yaml, packages/jahia/migrations/v31-32_assets/db-to-vfs.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2433
=> PAAS-2433: add package to migrate datastore to shared FS

mixins/jahia.yml, packages/jahia/jahia-rolling-redeploy.yml, packages/jahia/jahia-rolling-restart.yml, packages/jahia/migrations/migrate-to-v31.yaml, packages/jahia/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2258
Short description: Add new modules check for upgrades, migration and rolling restart/redeploy.
=> PAAS-2258: add modules check

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v31.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2565
=> PAAS-2565: fix shiro/csrf/graphql security issues

packages/jcustomer/jcustomer-rolling-upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2571
=> PAAS-2571: add jCustomer rolling upgrade package

packages/jcustomer/jcustomer-rolling-upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2571
=> PAAS-2571: remove env wide datadog monitor muting

packages/jahia/migrations/migrate-to-v31.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2565
=> PAAS-2565: fix v31 migration script

packages/jahia/migrations/migrate-to-v31.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2565
=> PAAS-2565: fix shiro version regex

packages/jahia/migrations/migrate-to-v32.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2433
=> PAAS-2433: add missing ignoreModules setting to v32 migration package

packages/jahia/migrations/migrate-to-v34.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2547
=> PAAS-2547: update v34 package to use check modules

packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2577
=> PAAS-2577: call queryShutdownEndpoint in onBeforeRedeployContainer[cp]

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2528
=> PAAS-2528: improve checkModules action

packages/jahia/consistency-check.yml, packages/jahia/migrations/migrate-to-v32.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2590
=> PAAS-2590: Upgrade SAM to 3.0.0

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v32.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2613
=> PAAS-2613: add storage node distribution accross AZ

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2616
=> PAAS-2616: change Installed and Resolved module state to Stopped

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2586
=> PAAS-2586: Install jExperience 3.3.0 instead of 3.2.0 for jCustomer v2

packages/one-shot/paas-2426-upgrade-jcustomer-to-v2.yaml, packages/one-shot/paas-2426-upgrade-jexperience-to-3-3-0.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2585
=> PAAS-2585: update jCustomer v2 upgrade package

assets/common/check_before_hn_upgrade.py
JIRA issue: https://jira.jahia.org/browse/PAAS-2618
=> PAAS-2618 add logger parameter for check_hardwarenodes function

packages/one-shot/paas-2426-upgrade-jcustomer-to-v2.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2630
=> PAAS-2630: fix jCustomer v2 upgrade

mixins/common.yml, mixins/jcustomer.yml, packages/one-shot/paas-2631-retry-upgrade-jcustomer-to-v2.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2631
=> PAAS-2631: add one shot package to finish upgrade to jcustomer 2.4

packages/one-shot/paas-2631-retry-upgrade-jcustomer-to-v2.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2631
=> PAAS-2631: rename retry-upgrade-jcustomer-to-v2 package id

packages/one-shot/paas-2426-upgrade-jcustomer-to-v2.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2630
=> PAAS-2630: Remove setenv from redeploy.conf after upgrade

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v35.yaml, packages/jahia/migrations/v35_assets/strongswan_connections_status.py
JIRA issue: https://jira.jahia.org/browse/PAAS-2601
=> PAAS-2601: Fix bad ipsec connection custom check

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v35.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2364
=> PAAS-2364: fix format for nodes distribution

mixins/jcustomer.yml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v26.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2605
=> PAAS-2605: handle jCustomer restart gracefully

packages/common/backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2661
=> PAAS-2661 ignore vanished file(s) on rsync

packages/common/backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2661
=> PAAS-2661 fix rsync parameters

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2608
=> PAAS-2608: Add a generic action for provisioning API calls

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2608
=> PAAS-2608: fix typos

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2608
=> PAAS-2608: add pattern when looking for errors and fixed few mistakes

packages/jahia/disable_tcmalloc.yaml, packages/jahia/enable_tcmalloc.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2665
Short description: create two one-shot packages to enable / disable tcmalloc
=> PAAS-2665: create one-shots to enable/disable tcmalloc

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v35.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2666
=> PAAS-2666: Change min_collection_interval for GlusterFS datadog conf

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2642
=> PAAS-2642: Use provisioning API to handle RO/FRO

packages/jahia/migrations/migrate-to-v35.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2592
=> PAAS-2592: fix addDatadogSiteEnvvar in migration v35

mixins/jahia.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v36.yaml, packages/one-shot/paas-2325-rollback-from-g1gc-to-parallelgc.yml, packages/one-shot/paas-2325-switch-to-g1gc.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2325
=> PAAS-2325: swith to G1GC again

mixins/common.yml, packages/jahia/migrations/migrate-to-v36.yaml, packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2689
=> PAAS-2689: add environment file for datadog-agent service on all nodes

mixins/common.yml, packages/common/backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2701
=> PAAS-2701: run the JournalService deadlock fix on cp nodes too

mixins/common.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2705
=> PAAS-2705 fix sed expression for aws secret key

packages/one-shot/paas-2706-json-java-patch.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2706
=> PAAS-2706: add one shot package to patch json-java security issue

packages/one-shot/paas-2706-json-java-patch.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2706
=> PAAS-2706: fix json-java patch to avoid removing wrong file

packages/one-shot/paas-2706-json-java-patch.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2706
=> PAAS-2706: fix wrong check in paas-2706-json-java-patch.yaml

packages/common/backup.yml
JIRA issue: https://jira.jahia.org/browse/COPS-971
=> COPS-971 fix used region for lockfile in addMetadata

packages/jahia/migrations/migrate-to-v37.yaml, packages/jahia/migrations/v37_assets/set_dd_tags.sh
JIRA issue: https://jira.jahia.org/browse/PAAS-2655
=> PAAS-2655: obfuscate ES queries in Datadog APM configuration

packages/jahia/augmented-search-install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2712
=> PAAS-2712: fix issue with new JSON lib

mixins/jahia.yml, packages/common/restore.yml, packages/jahia/augmented-search-install.yml, packages/jahia/link-to-jcustomer.yml, packages/jahia/manage-module.yml, packages/jahia/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2609
=> PAAS-2609: use the provisioning API to manage modules

packages/jahia/link-to-jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2680
=> PAAS-2680: add jexperience probe test after jahia/jcustomer link

assets/common/hn_nodes_list.py, packages/common/start-nodes.yaml, packages/common/stop-nodes.yaml
Handle storage nodes in stop/start-node.yaml
JIRA issue: https://jira.jahia.org/browse/COPS-953
=> COPS-953: fix the way we fetch proxysql password in hn_nodes_list.py.

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2609
=> PAAS-2609: add missing quotes for module installation

packages/one-shot/paas-2717-json-java-rollback.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2717
=> PAAS-2717: add a package to rollback the java-json lib patch

packages/one-shot/paas-2717-json-java-rollback.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-XXX
=> PAAS-2717: not use the rolling restart package to avoid the issue with Karaf console

packages/one-shot/paas-2717-json-java-rollback.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2717
=> PAAS-2717: stop tomcat before deleting the json lib

packages/one-shot/paas-2717-json-java-rollback.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2717
=> PAAS-2717: fix if condition if json lib not present

packages/one-shot/paas-2719-upgrade-pat-to-1-4-1.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2719
=> PAAS-2719: call the right action when upgrading PAT to 1.4.1

packages/jahia/migrations/migrate-to-v37.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2719
=> PAAS-2719: Update PAT 1.4.0 to 1.4.1

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v37.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2710
=> PAAS-2710: use kibana-dashboards-provider/1.2.0

mixins/elasticsearch.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2723
=> PAAS-2723: no Elastic Cloud related actions if customer is LOIM

packages/jahia/migrations/migrate-to-v37.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2731
=> PAAS-2731: Remove switch to G1GC from next migration package

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2734
=> PAAS-2734: Add timeout in queryShutdownEndpoint action

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2723
=> PAAS-2723: fix restore EOF

packages/one-shot/paas-2738-json-java-custom-patch.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2738
=> PAAS-2738: Add one-shot package to apply JSON lib custom patch

mixins/elasticsearch.yml, packages/jcustomer/install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2454
=> PAAS-2454: use a script to populate geoname index instead of jcustomer 

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v38.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2691
=> PAAS-2691: fix Datadog product tag

packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v28.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2742
=> PAAS-2739 bump to jcustomer v28 (v27 already released)

packages/jahia/migrations/migrate-to-v38.yaml, packages/jcustomer/migrations/migrate-to-v28.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2742
=> PAAS-2742 fix wrong variable name in migration scripts

assets/common/rclone-logs.sh, packages/jahia/migrations/migrate-to-v38.yaml, packages/jcustomer/migrations/migrate-to-v28.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2739
=> PAAS-2739 retry sending logs to logs bucket if an error occurs

assets/common/log_events.sh, mixins/common.yml, packages/jahia/migrations/migrate-to-v38.yaml, packages/jcustomer/migrations/migrate-to-v28.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2746
=> PAAS-2746 use DD_SITE envvar when using datadog's API

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2690
=> PAAS-2690 add a fix for indices's alias and lifecycle settings if needed

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2760
=> PAAS-2760: redirect useless output to /dev/null when restoring ES backup

packages/jahia/migrations/migrate-to-v38.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2677
=> PAAS-2677: fix v38 migration package for envs without AS

packages/jcustomer/migrations/v28_assets/jcustomer_custom_metrics.py
JIRA issue: https://jira.jahia.org/browse/PAAS-2657
=> PAAS-2657: add new check to count indices size per jcustomer env

packages/jahia/augmented-search-install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2688
=> PAAS-2688: fix AS install because of esEndpoint variable

packages/jahia/augmented-search-install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2688
=> PAAS-2688: fix AS install because of missing API token

packages/jahia/migrations/v38_assets/augmented_search.py
JIRA issue: https://jira.jahia.org/browse/PAAS-2688
=> PAAS-2688: only count languages on processing node

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2658
=> PAAS-2658: fix sudoers update for dd-agent

assets/common/hn_upgrade_plan.py
JIRA issue: https://jira.jahia.org/browse/PAAS-1014
=> COPS-1014: add script to make a plan for the upgrade

assets/common/hn_upgrade_plan.py
JIRA issue: https://jira.jahia.org/browse/PAAS-2788
=> PAAS-2788: fix wrong default param in hn_upgrade_plan.py

packages/jahia/migrations/v38_assets/augmented_search.py
JIRA issue: https://jira.jahia.org/browse/PAAS-2658
=> PAAS-2658: fix AS custom check to send metrics on proc only for specific metrics

mixins/common.yml, packages/common/start-nodes.yaml, packages/common/stop-nodes.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2789
=> PAAS-2789: improve start/stop nodes packages for environments with single sqldb/storage node

packages/common/start-nodes.yaml, packages/common/stop-nodes.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2789
=> PAAS-2789: take care of proc node for environments with single sqldb/storage node

packages/common/start-nodes.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2789
=> PAAS-2789: fix caption for start-nodes package

mixins/jahia.yml, packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2809
=> PAAS-2809: add check on karaf config files before/after jahia restart

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2809
=> PAAS-2809: improve formating of karaf config error log

packages/jahia/migrations/migrate-to-v38.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2819
=> PAAS-2819: fix touch command in ProxySQL service override

packages/jahia/migrations/migrate-to-v38.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2833
=> PAAS-2833: fix addESCredentialsAsEnvvar action in v38 Jahia migration

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v39.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2821
=> PAAS-2821: Add timezone to JVM options

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2821
=> PAAS-2821: correct JVM timezone option

packages/common/backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2810
=> PAAS-2810 allow apostrophe for displayname on backrest call

packages/jahia/update-graphql-dxm-provider.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2843
=> PAAS-2843: add package to update grqphql-dxm-provider

packages/jahia/migrations/migrate-to-v39.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2821
=> PAAS-2821: Correct migration package

packages/jahia/update-graphql-dxm-provider.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2843
=> PAAS-2843: improve package to update grqphql-dxm-provider

packages/jahia/update-graphql-dxm-provider.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2843
=> PAAS-2843: fix stupid oversight in package to update grqphql-dxm-provider

packages/jahia/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2805
=> PAAS-2805: fix upgrade package with dx-clustering upgrade

assets/common/hn_upgrade.py
JIRA issue: https://jira.jahia.org/browse/PAAS-2861
=> PAAS-2861: add multithreading when stopping/starting nodes during hn upgrade

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2868
=> PAAS-2868 bump to jexperience 2.10.0 for jcustomer v1

assets/common/hn_upgrade.py
JIRA issue: https://jira.jahia.org/browse/PAAS-1090
=> COPS-1090: Improve hn_upgrade script

packages/jahia/jahia-rolling-restart.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2610
=> PAAS-2610 add common mixins to jahia rolling restart manifest

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2869
=> PAAS-2869: fix jcustomer 2.4.0 restore

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2825
=> PAAS-2825: fix distributed-sessions cluster status after env upgrade

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-XXX
=> PAAS-2869: fix typo

assets/common/hn_upgrade_plan.py
JIRA issue: https://jira.jahia.org/browse/PAAS-2879
=> PAAS-2879: fix groups generation in hn upgrade plan script

packages/jahia/augmented-search-install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2884
=> PAAS-2884: Install AS 3.6.0 for Jahia 8.1.3+ and 3.4.2 otherwise + clean code

packages/one-shot/paas-2883-spring-web-patch.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2883
=> PAAS-2883 patch spring-web lib

packages/one-shot/paas-2883-spring-web-patch.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2883
=> PAAS-2883 still stop tomcat manually

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2886
=> PAAS-2886: Install jExperience 2.10.1 and 3.3.1

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2869
=> PAAS-2869: fix jcustomer 2.4 lost aliases bug at restoration

packages/one-shot/paas-2883-spring-web-patch.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2883
=> PAAS-2883 add modules state check

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2869
=> PAAS-2869: fix jCustomer restore

packages/jcustomer/set-unomi-root-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2874
=> PAAS-2874: fix jcustomer password reset

mixins/common.yml, mixins/haproxy.yml, mixins/jahia.yml, mixins/mariadb.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2891
=> PAAS-2891: add retries to curl commands in installation actions

packages/one-shot/paas-2911-fix-storage-nodes-cloudlets.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2911
=> PAAS-2911 add one-shot package for fixing the storage nodes cloudlets

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2908
=> PAAS-2908: fix jdk options setting for jahia 8 at upgrade

mixins/jcustomer.yml, packages/jcustomer/install.yml, packages/jcustomer/update-events.yml
restart when udpating unomi allowed IPs
JIRA issue: https://jira.jahia.org/browse/PAAS-2442
=> PAAS-2442: fix jcustomer post restart event and disable jcustomer

packages/jcustomer/geolite-database-update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2903
=> PAAS-2903: update geolite db package

packages/jcustomer/migrations/migrate-to-v30.yaml, packages/jcustomer/migrations/v30_assets/jcustomer_status.py
JIRA issue: https://jira.jahia.org/browse/PAAS-2517
=> PAAS-2517: remove jcustomer status check following haproxy nodes

packages/jcustomer/migrations/migrate-to-v30.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2517
=> PAAS-2517: fix typo in jcustomer v30 migration

packages/jcustomer/migrations/migrate-to-v30.yaml, packages/jcustomer/migrations/v30_assets/jcustomer_node_not_in_haproxy.py, packages/jcustomer/migrations/v30_assets/jcustomer_node_not_in_haproxy.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2520
=> PAAS-2520 add jcustomer_node_not_in_haproxy custom check

packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v30.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2442
=> PAAS-2442: add HAPROXY_NODES_COUNT env var to jcustomer nodes

packages/jcustomer/migrations/migrate-to-v30.yaml, packages/jcustomer/migrations/v30_assets/jcustomer_node_not_in_haproxy.py, packages/jcustomer/migrations/v30_assets/sudoers_dd_agent
JIRA issue: https://jira.jahia.org/browse/PAAS-2520
=> PAAS-2520 fix dd's user not able to get haproxy count and start tcpdump

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2931
=> PAAS-2931: Install jExperience 2.10.2 instead of 2.10.1

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v41.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2926
=> PAAS-2926: remove duplicate of provisionning and jcrcommands modules

mixins/jahia.yml, packages/common/restore.yml, packages/jahia/migrations/migrate-to-v41.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2905
=> Paas 2905 switch datadog GC from jahia's job to systemd's timer

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v41.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2905
=> PAAS-2905 fix switch disabling job not done after restore legacy backup

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2905
=> PAAS-2905 fix test that can exit !=0

packages/one-shot/paas-2925-fix-dumpS_path_typo.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2925
=> PAAS-2925 add one-shot package fixing the dumps_path typo

mixins/common.yml, packages/jahia/migrations/migrate-to-v41.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2531
=> PAAS-2531: add an action to check browser tests in migration packages

packages/one-shot/paas-2925-fix-dumpS_path_typo.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2940
=> PAAS-2940 force /var/tmp/cloud ownership

mixins/common.yml, mixins/mariadb.yml, packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v41.yaml, packages/jahia/redeploy-galera-nodes.yml, packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2932
=> PAAS-2932 upgrade sqldb to alamalinux images

mixins/elasticsearch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2915
=> PAAS-2915: remove sed on karaf service file for ES setup

packages/jahia/install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2954
=> PAAS-2954: Fix cloudlets count for storage nodes

packages/jahia/migrations/migrate-to-v41.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2939
Short description: Update app-shell module to 2.9.0 for Jahia 8.1.3 to 8.1.6
=> PAAS-2939: Update app-shell module

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2942
=> PAAS-2942: add missing TransformerFactory parameter to CATALINA_OPTS to fix DS module with Jahia 8.2

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2966
=> PAAS-2966: move jahia 8.2 catalina_opts options to dockerfile

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2965
=> PAAS-2965: fix Jahia startup check script starting too fast sometimes

packages/jahia/migrations/migrate-to-v41.yaml, packages/jahia/migrations/v41_assets/jahia_privileged_users_count.groovy
JIRA issue: https://jira.jahia.org/browse/PAAS-2906
=> PAAS-2906 fix groovy script not writing the result in file

packages/jahia/migrations/migrate-to-v41.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2906
=> PAAS-2906 add the special cloudscript fix

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2965
=> PAAS-2965: improve logging for startupJahiaHealthCheck

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v41.yaml, packages/jahia/migrations/migrate-to-v42.yaml, packages/jahia/migrations/migrate-to-v43.yaml, packages/jcustomer/migrations/migrate-to-v30.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2971
=> PAAS-2971: split v41 migration into 3 migration packages

packages/jahia/migrations/migrate-to-v42.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2971
=> Paas 2971 fix db migration

packages/jahia/install.yml, packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2982
=> PAAS-2982: fix centos repos

packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2986
=> PAAS-2986 add /etc/locale.conf sourcing to fetch JAHIA_UPGRADE value

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2992
=> PAAS-2992: Increase timeout on Jahia startup

packages/one-shot/paas-2993-spring-web-patch5.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2993
=> PAAS-2993: Add one-shot package for spring-web lib patch

mixins/mariadb.yml, packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2991
=> PAAS-2991 add a way to restore a previous minor MariaDB backup

assets/database/mysql-init.d
JIRA issue: https://jira.jahia.org/browse/PAAS-2998
=> PAAS-2998: fix qpress install for centos

assets/database/mysql-init.d
JIRA issue: https://jira.jahia.org/browse/PAAS-2998
=> PAAS-2998: fix qpress install for centos fix

mixins/mariadb.yml, packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2999
=> PAAS-2999 back to the 90s for dealing with mysql dæmon

mixins/common.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2989
=> PAAS-2989: Fix bug when muting monitors by tags

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v43.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-3004
=> PAAS-3004: check if SAM is started after refresh

mixins/mariadb.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-3015
=> PAAS-3015: fix backup restoration for centos nodes

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-3021
=> PAAS-3021: store new ES password for AS account at restore

mixins/jahia.yml, packages/jahia/manage-module.yml, packages/jahia/update-jexperience.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-3014
=> PAAS-3014: Install jExperience 3.4.0 with jCustomer 2 and Jahia 8.1 

packages/jahia/migrations/migrate-to-v42.yaml, packages/one-shot/PAAS-3037-and-PAAS-3038-redeploy-storage-nodes-to-almalinux-and-trigger-mariadb-upgrade-if-needed.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-3038
=> PAAS-3038 do mariadb-upgrade if needed

mixins/jahia.yml, packages/jahia/augmented-search-install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-3029
=> PAAS-3029 add an action allowing you to modify a karaf module configuration, ensuring that it is properly replicated within the cluster

mixins/mariadb.yml, packages/jahia/update-events.yml
service before jahia startup in onAfterStart event
JIRA issue: https://jira.jahia.org/browse/PAAS-3041
=> PAAS-3041: disable tomcat service before env stop and add start mariadb

packages/jahia/update-events.yml
beforeStop/afterStart events
JIRA issue: https://jira.jahia.org/browse/PAAS-3041
=> PAAS-3041: disable/enable proxysql along with tomcat in

packages/common/manage-cloudlets.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-2997
=> PAAS-2997: add delay between storage nodes cloudlets update

packages/jahia/update-events.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-3062
=> PAAS-3062: fix galera cluster nodes startup in onAfterStart event

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-3059
Short description: fix bug in checkModule action and correct annoying typo
=> PAAS-3059: Fix bug in checkModule action

packages/jahia/augmented-search-install.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-3069
=> PAAS-3069: Update database-connector and elasticsearch-connector

assets/haproxy/haproxy-jcustomer-cloud.cfg, mixins/haproxy.yml, packages/jcustomer/install.yml, packages/jcustomer/migrations/migrate-to-v31.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2962
=> PAAS-2962: Add sticky session for jCustomer

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v44.yaml, packages/jahia/migrations/v44_assets/karaf_openssl.cnf
JIRA issue: https://jira.jahia.org/browse/PAAS-3008
=> PAAS-3008: add ssh options for karaf console on almalinux

packages/jahia/migrations/migrate-to-v44.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2673
=> PAAS-2673: fix storage node cloudlet condition in v44 migration

packages/jahia/migrations/migrate-to-v44.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-3012
=> PAAS-3012: enable page composer on jahia 8.2

packages/jcustomer/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-3074
=> PAAS-3074: add data migration to jCustomer upgrade

assets/haproxy/haproxy-jahia-cloud.cfg, assets/haproxy/haproxy-jcustomer-cloud.cfg, packages/jahia/migrations/migrate-to-v44.yaml, packages/jcustomer/migrations/migrate-to-v31.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-3036
=> PAAS-3036: Capture cookie in HAProxy

mixins/jcustomer.yml, packages/jcustomer/migrations/migrate-to-v31.yaml, packages/jcustomer/migrations/v31_assets/karaf_openssl.cnf
JIRA issue: https://jira.jahia.org/browse/PAAS-3077
=> PAAS-3077: add ssh options for karaf console on almalinux for jcustomer

packages/jcustomer/launch-unomi-migration.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-3073
=> PAAS-3073: add package to launch unomi migration

mixins/jcustomer.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-3077
=> PAAS-3077: Fix path in disablejCustomerKarafLogin

packages/jcustomer/set-log-level.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-3080
=> PAAS-3080: Add Jelastic package to set log level on jCustomer

packages/jahia/migrations/migrate-to-v44.yaml, packages/jahia/migrations/v44_assets/thread-dump.sh
JIRA issue: https://jira.jahia.org/browse/PAAS-3033
=> PAAS-3033: add classes dump to cron

packages/jahia/install.yml, packages/jahia/migrations/migrate-to-v44.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2584
=> PAAS-2584: set 60% ratio for ram/XMX

mixins/jahia.yml, packages/jahia/migrations/migrate-to-v44.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2842
=> PAAS-2842: Restart tomcat after an OOM

packages/jahia/migrations/migrate-to-v44.yaml, packages/jahia/migrations/v44_assets/thread-dump.sh
JIRA issue: https://jira.jahia.org/browse/PAAS-3033
=> PAAS-3033 makes thread-dump.sh compatible with java17 images

packages/jcustomer/launch-unomi-migration.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-3073
=> PAAS-3073: Add skipable backup step to unomi-launch-migration package

packages/jcustomer/upgrade-to-v2.yaml, packages/jcustomer/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-3075
=> PAAS-3075: Fix permission issue

assets/jahia/org.jahia.modules.jexperience.settings-global.cfg, packages/jahia/migrations/migrate-to-v44.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2458
=> PAAS-2458: configure proxy mode for jExperience

packages/jahia/migrations/migrate-to-v44.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-2996
- Update SAM
- Decrease RenderingChain probe severity from critical to high
=> PAAS-2996: Update SAM to 2.8.0 / 3.2.0

packages/common/restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-3028
=> PAAS-3028: fix installBackupTools during restore

packages/jahia/migrations/migrate-to-v44.yaml
=> PAAS-3048: fix mariadb health check for v44 migration

mixins/mariadb.yml, packages/jahia/migrations/migrate-to-v44.yaml
=> PAAS-3048: fix mariadb health check

packages/jahia/migrations/migrate-to-v44.yaml, packages/jahia/migrations/v44_assets/override.conf
JIRA issue: https://jira.jahia.org/browse/PAAS-1898
=> PAAS-1898: clean lock files during Jahia startup

packages/jahia/migrations/migrate-to-v44.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1898
=> PAAS-1898: add action to clean lock files to migration v44

packages/jahia/migrations/migrate-to-v44.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-1898
=> PAAS-1898: fix cleanLockFilesAtJahiaStartup in migration v44

assets/database/bootstrap.conf, assets/database/override.conf, mixins/mariadb.yml, packages/common/restore.yml, packages/jahia/update-events.yml
=> PAAS-3048: fix Jelastic auto bootstrap of Galera cluster

packages/jcustomer/migrations/migrate-to-v31.yaml, packages/jcustomer/migrations/v31_assets/karaf_override.lib
JIRA issue: https://jira.jahia.org/browse/PAAS-3103
=> PAAS-3103 update jelastic karaf override

mixins/mariadb.yml
=> PAAS-3048: fix startGaleraNode not starting the node

mixins/mariadb.yml, packages/common/restore.yml
=> PAAS-3048: fix restore not working because of Galera startup

mixins/mariadb.yml
=> PAAS-3048: add missing space in rollingRestartGaleraNodes

packages/jahia/migrations/migrate-to-v44.yaml, packages/jahia/migrations/v44_assets/dd_agent_tomcat_conf.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-3111
=> PAAS-3111: fix multiline processing for Tomcat logs

mixins/mariadb.yml
=> PAAS-3048: fix installDatabase not working because of a comment on last line of cmd block

mixins/mariadb.yml, packages/jahia/migrations/migrate-to-v44.yaml
=> PAAS-3048: disable httpd on sqldb to prevent php-fpm from starting

packages/jahia/migrations/migrate-to-v44.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-3105
=> PAAS-3105 update modules related to SEC-104

packages/jahia/migrations/migrate-to-v44.yaml
This reverts commit 1fa830eccf0c809c2d3062d9d782cd3b0d164772.
JIRA issue: https://jira.jahia.org/browse/PAAS-3105
=> Revert "PAAS-3105 update modules related to SEC-104"

mixins/jahia.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-3105
=> PAAS-3105 Fix files selection for remove ignored modules

packages/jahia/migrations/migrate-to-v44.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-3120
=> PAAS-3120: use graphql-dxm-provider 2.19.0 for jahia < 8.1.6.0

packages/jahia/migrations/migrate-to-v44.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-3124
=> PAAS-3124: Move mariadb systemd fix to the begining of v44 migration

mixins/common.yml
=> PAAS-3048 fix setGlobalRepoRootUrl regexp

mixins/mariadb.yml, packages/jahia/migrations/migrate-to-v44.yaml, packages/jahia/migrations/v44_assets/init-mysql, packages/jahia/update-events.yml
=> PAAS-3048: fix bootstrap of galera cluster not working after v44 migration

mixins/mariadb.yml, packages/jahia/migrations/migrate-to-v44.yaml
=> PAAS-3048: exterminate phpmyadmin once and for all (and fix bugs)

mixins/mariadb.yml
=> PAAS-3048: fix redeployGaleraClusterNodes for single DB

mixins/mariadb.yml, packages/common/restore.yml
=> PAAS-3048 allow restore on pre v3.36.0 release

mixins/mariadb.yml, packages/common/restore.yml
=> PAAS-3048 use md5 hash to determine how to start mariadb

packages/jcustomer/reindexation.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-3136
=> PAAS-3136: Fix reindex bug when lifecycle isn't configured

packages/one-shot/paas-3135-fix-graalvm-and-setenv-symlink.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-31315
=> PAAS-3135: fix GraalVM conf for Jahia 8

mixins/common.yml, packages/jahia/migrations/migrate-to-v45.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-3079
=> PAAS-3079: check external domains before/after migration

packages/jahia/migrations/migrate-to-v45.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-3105
=> PAAS-3105: Update modules

packages/jahia/migrations/migrate-to-v45.yaml
JIRA issue: https://jira.jahia.org/browse/PAAS-3135
=> PAAS-3135: set setenv.sh as a symlink of tomcat-env.sh

packages/jahia/migrations/migrate-to-v45.yaml, packages/jahia/upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-3151
=> PAAS-3151 update setenv.sh on migration to 8.2

.github/pull_request_template.md, mixins/jcustomer.yml
=> PAAS-3141: fix reapplyPatches action

mixins/jahia.yml, mixins/jcustomer.yml, packages/jcustomer/install.yml, packages/jcustomer/update-events.yml, packages/jcustomer/upgrade-to-v2.yaml, packages/jcustomer/upgrade.yml
=> PAAS-3173: make sure migrations are done properly during jcustomer upgrade

packages/jahia/migrations/migrate-to-v45.yaml
=> PAAS-3167: fix updateClassesDumpGeneration because of Cloudscripting

mixins/jahia.yml
=> PAAS-3153: improve dumpModules, checkModulesAfterOperation and callProvisioningAPI

mixins/jahia.yml
=> PAAS-3153: fix checkModulesAfterOperation when a file doesn't exist

packages/jahia/migrations/migrate-to-v45.yaml
=> PAAS-3148 bump distributed sessions to v4.2.0

mixins/jcustomer.yml
=> PAAS-3173: fix typo in checkJcustomerHealthWhenStarting action

assets/common/sockd.conf, packages/jahia/disable-tomcat-filtering.yaml, packages/jahia/enable-tomcat-filtering.yaml
=> PAAS-3177 - switch to proxychains+dante outbound filltering methode

assets/common/sockd.conf
Short description: added following discussion with product team
=> Paas-3177  allow maven repos on dante server

packages/jahia/enable-tomcat-filtering.yaml
=> PAAS-3177 fix not working well capabilities removing

packages/jcustomer/upgrade-to-v2.yaml, packages/jcustomer/upgrade.yml
=> PAAS-3154: Make jCustomer upgrade to snapshot version work

packages/one-shot/paas-3193-fix-kibana-dashboards.yaml
=> PAAS-3193 add fix kibana dashboards one-shot package

packages/one-shot/paas-3212-update-forms-core-and-jcontent-module.yaml, packages/one-shot/paas-3212-update-forms-core-to-3-14.yaml
=> PAAS-3212: one shot package to update forms-core to 3.15

mixins/jahia.yml
=> PAAS-3187: Install jExperience 3.5.1

mixins/jahia.yml
=> PAAS-3229 handles cases where the moduleDump file doesn't exist

packages/one-shot/paas-3239-enable-jcustomer-filtering.yaml
=> PAAS-3239 add jcustomer enabling filtering one-shot package

assets/common/sockd.conf
=> PAAS-3239 add missing elastic-cloud.com allowed dests on sockd.conf

packages/jcustomer/disable-jcustomer-filtering.yaml, packages/jcustomer/enable-jcustomer-filtering.yaml
=> PAAS-3237: add packages to enable/disable jcustomer filtering
